### ISSUE TITLE
[提议]将和谐图片直接以连接形式录入 不使用图片形式

### ISSUE THREAD

**Issue by xioxin** [Mapaler/EhTagTranslator#11]
希望在 “ehTag构建者” 中将连接地址解析为图片

一些可以被github加载的h图 直接采用连接的形式 防止被直接展示

图片：`![图片](地址)`
连接：`[图片](地址)`

顺便 是不是应该限制下图片的数量 像蓝白胖次里面的图真是太多了

**Comment by Mapaler** [comment]
链接转为图片可能会让将来的扩展不好继续，因为JS版可以完全远样显示简介，所以链接也是可以存在的。我想其他办法解决吧。
胖次图是添加太多了，一添加起来就停不下了，删掉一些吧。

**Comment by Mapaler** [comment]
要不通过在图像路径后面添加特殊识别符？生成CSS时自动去掉那个特殊识别符。如果同意的话你建议用什么符号？

**Comment by xioxin** [comment]
`#` 
![](http://i.imgur.com/mMi9qyE.jpg)

![](#http://i.imgur.com/mMi9qyE.jpg)

```
![](http://i.imgur.com/mMi9qyE.jpg)

![](#http://i.imgur.com/mMi9qyE.jpg)
```

**Comment by Mapaler** [comment]
毕竟还是图样，除了http和https，其他协议的都不会产生图片地址，自己看源代码。

我觉得为了方便只能添加在扩展名后，而且?#等特殊字符并不会改变图片实际地址。

**Comment by xioxin** [comment]
![好孩子看不到](#)

```
![好孩子看不到](# "http://i.imgur.com/mMi9qyE.jpg")
```

查看源代码 看title
这样可以吗 地址放到了图片的title里了

**Comment by Mapaler** [comment]
虽然这样也可以，但必须加上引号的话会不会很花时间？

**Comment by xioxin** [comment]
![http://i.imgur.com/mMi9qyE.jpg](#)

```
![http://i.imgur.com/mMi9qyE.jpg](#)
```

直接alt
不过 这样会导致页面很多乱七八糟的连接 显示很乱

**Comment by Mapaler** [comment]
是的，很乱，所以不会采用这种方式。
`![图](http://i.imgur.com/mMi9qyE.jpgi)`
这样如何，在最后面加上一个i，反正基本没扩展名是以i结尾的吧？或者加h？

**Comment by xioxin** [comment]
这种方法我感觉不好
并且 如果连接是空的话不会发起请求 可以加快wiki的打开速度

**Comment by Mapaler** [comment]
为什么不好呢，写起来不是快很多么？后面那个是这样(然而我现在都是用git在本地编辑了，反正都不预览)。

**Comment by Mapaler** [comment]
这边已经弄好了，你看看吧。
`![替换文字](# "图片网址")`和`![图片](http://ehgt.org/c/botm5.jpgh)`都支持

**Comment by xioxin** [comment]
晚上回家测试 :joy:

**Comment by Mapaler** [comment]
你的表情从哪儿来的？

**Comment by xioxin** [comment]
输入冒号 有提示
具体名字可以参考 http://emoji.muan.co/
