### ISSUE TITLE
似乎不支持里站https

### ISSUE THREAD

**Issue by Ai-Himmel** [Mapaler/EhTagTranslator#12]
css样式里的里站都是http://...只有我？
![](http://ww4.sinaimg.cn/large/0060lm7Tgw1f6elolzt4sj30tr03dwet.jpg)

**Comment by Ai-Himmel** [comment]
@Mapaler

**Comment by Ai-Himmel** [comment]
@Mapaler

**Comment by Mapaler** [comment]
我当时写的时候还不需要https呢，你可以先自己把https加上，我这会儿改程序

**Comment by Mapaler** [comment]
已经更新，试试？
