### ISSUE TITLE
重名的tag怎么解决？

### ISSUE THREAD

**Issue by OpportunityLiu** [Mapaler/EhTagTranslator#16]
比如 eris （爱丽丝/玩伴猫耳娘）（厄里斯/为美好的世界献上祝福！）

**Comment by OpportunityLiu** [comment]
有没有办法根据parody切换？

**Comment by Mapaler** [comment]
没有，本来E站就没有分，你要搜索特殊作品里的爱丽丝，就应该同时用两个tag搜索。

**Comment by OpportunityLiu** [comment]
我知道没有分，但是两者的中文译名不一样，在翻译里应该怎么写？

**Comment by Mapaler** [comment]
你直接写两个介绍不就行了么，“爱丽丝\\|厄里斯”，都是音译啦

**Comment by Mapaler** [comment]
强迫症患者连大小写都忍不了

**Comment by OpportunityLiu** [comment]
好吧，终于进入转义字符的时代了。。。

**Comment by OpportunityLiu** [comment]
感觉需要修改一下重复tag的处理逻辑啊，现在角色都是按照原作组织的，强行在一个格子里挤两部作品的角色名直接把这个结构毁了啊。
`爱丽丝 | 厄里斯`
这种东西应该交给脚本来拼吧。。

**Comment by Mapaler** [comment]
问题是E绅网页源代码里这两个没有任何区别啊，无法区分。再说，同一个英文名干嘛非要翻译成两个不同的中文名，要是这样那港台陆翻译不同的不是要打起来了？

**Comment by OpportunityLiu** [comment]
目前的情况是闪乱神乐的chitose和舰娘的chitose重复了，这两个属于翻译一样但是简介不同的

**Comment by OpportunityLiu** [comment]
爱丽丝 | 厄里斯 这个是不同作品里的不同翻译

**Comment by Mapaler** [comment]
介绍不一就写两份简介放一起。同一个角色不同汉化组的汉字还不一样呢，何况不同的作品里的。就是同一个名字别纠结了

**Comment by OpportunityLiu** [comment]
。。。现在tag是按照作品组织的，怎么放一起？

**Comment by OpportunityLiu** [comment]
https://ehwiki.org/wiki/murakumo
还有这种直接冲突的

**Comment by OpportunityLiu** [comment]
我来写个workaround你看一下吧。。。

**Comment by Mapaler** [comment]
其实都归结于E站同样英文的tag除了大分类不同代码上不同外，其他没有任何区别，所以无法区分。你看连E站自己的wiki都同时写的两个，你要我怎么去区分呢。
你简介可以写成

> 名字1（作品1）\<br\>名字2（作品2）\<br\>图1\<br\>图2

**Comment by OpportunityLiu** [comment]
https://github.com/Mapaler/EhTagTranslator/pull/17

**Comment by OpportunityLiu** [comment]
js基本不会，但是我的意思应该表达清楚了

**Comment by OpportunityLiu** [comment]
#17
