### ISSUE TITLE
重名的角色怎么办

### ISSUE THREAD

**Issue by sj9481** [Mapaler/EhTagTranslator#18]
今天看见一个和榛名的英文名字重名了 叫春奈 是《这个是僵尸吗?》的角色

**Comment by OpportunityLiu** [comment]
`| 英文名  |  中文名1 \| 中文名2   |  介绍1<br>介绍2  | `

**Comment by OpportunityLiu** [comment]
还有你注意一下，英文标签是不会出现大写字母的

**Comment by sj9481** [comment]
明白了 知道不会出现大写 已经加了二十多个词了 就是有些角色的名字很难找

**Comment by OpportunityLiu** [comment]
还是在竖线两侧加个空格吧，排版好看一点
`| 英文名 | 中文名1 \| 中文名2 | 介绍1<br>介绍2 |`

**Comment by OpportunityLiu** [comment]
之前的讨论 #16 #17

**Comment by Mapaler** [comment]
为什么我只收到 OpportunityLiu 的邮件，没有 sj9481 的邮件？
![](http://ww4.sinaimg.cn/large/6c84b2d6gy1ffwiicc5bzg20s20913yu.gif)

**Comment by OpportunityLiu** [comment]
把这个帖子写到wiki主页里吧

**Comment by Mapaler** [comment]
已经写了
