### ISSUE TITLE
能弄个无图版吗

### ISSUE THREAD

**Issue by dodying** [Mapaler/EhTagTranslator#2]
生成CSS能不能不加入图片

**Comment by dodying** [comment]
泼冷水....
感觉并不会有多少人来编辑...
添加了几个我就放弃了

**Comment by dodying** [comment]
此外CSS也不能检查更新吧...

**Comment by Mapaler** [comment]
你希望不要生成简介么？还是只是不生成图片。如果是需要这样的扩展需求的话，可以做个设置窗口。
你也可以做推广啊，每个人都可以添加的，你让每个人添加两个，这样添加的总会多起来。
CSS不能检查更新，这个当然就是用户发现自己有需要的TAG没有的时候，就自己来更新CSS就行了。
其实是从纯JS的计划演变为CSS的，JS需要做的功能多很多，而且更耗资源。不过如果特别有需求做JS版也行。或者还是将Builder移植到E绅士网站更方便呢。这些决策和开发都是很花时间的，而且花了很多时间也并不一定有人会用。

**Comment by Mapaler** [comment]
你希望不要生成简介么？还是只是不生成图片。如果是需要这样的扩展需求的话，可以做个设置窗口。
你也可以做推广啊，每个人都可以添加的，你让每个人添加两个，这样添加的总会多起来。
CSS不能检查更新，这个当然就是用户发现自己有需要的TAG没有的时候，就自己来更新CSS就行了。
其实是从纯JS的计划演变为CSS的，JS需要做的功能多很多，而且更耗资源。不过如果特别有需求做JS版也行。或者还是将Builder移植到E绅士网站更方便呢。这些决策和开发都是很花时间的，而且花了很多时间也并不一定有人会用。

**Comment by dodying** [comment]
只是不生成图片...

**Comment by Mapaler** [comment]
话说，你添加自己喜爱的作者，光名字，可能你认识，但是别人可不一定认识，所以我都是加入了作者作品的封面，一看画风，别人可能也会想“哦，原来是画这个作品的作者，我见过”之类的。

**Comment by Mapaler** [comment]
设置功能，等我下周工作日有时间再开发。

**Comment by dodying** [comment]
感谢

**Comment by Mapaler** [comment]
搞好了

**Comment by dodying** [comment]
试了一下，
设置只勾选“生成简介”的话，EX的标签空白，没有译名
设置勾选“生成简介”与“生成简介图片”的话，EX的标签无译名，有图片的话，显示图片...
貌似连简介里的文字也不能显示
还有以前不是移动到标签上才显示简介的吗

**Comment by SweetLoli** [comment]
我刚刚也遇到了这样的问题，不过重置一下就好了……

**Comment by dodying** [comment]
怎么重置？
我暂时切回上一个版本了

**Comment by SweetLoli** [comment]
“E绅士标签构建者 设置”窗口的左下角有个“重置”按钮，按了后“Tag通用样式”里就出现了代码，最后“保存”就好啦~

**Comment by dodying** [comment]
莫非刚才错误是因为我之前生成Css的时候，“Tag通用样式”为空
多谢了

**Comment by Mapaler** [comment]
我刚刚把这个问题解决了，就是新用户设置没有初始化，所以重置一下就好了。（因为我把之前的一些固定的东西改成了自定义）

**Comment by Mapaler** [comment]
我感觉变成了给我科普舰娘人物的了
![image 4](https://cloud.githubusercontent.com/assets/6565860/15287283/64a13b86-1b94-11e6-8b5f-5f19ab74bccb.jpg)

**Comment by dodying** [comment]
只是最近有下过这些舰C角色的一些本子...
话说国外有什么好的图床吗，毕竟我们上的都是被强了的和谐站，也不怕图床网站被强

**Comment by Mapaler** [comment]
不知道，只知道微博图床最方便了。

**Comment by dodying** [comment]
嗯嗯，总之多谢
