### ISSUE TITLE
Git编辑Wiki密钥

### ISSUE THREAD

**Issue by Mapaler** [Mapaler/EhTagTranslator#20]
刚才试了 Deploy keys ，可以让其他用户直接Git编辑Wiki，但是缺点就是也同时可以编辑主程序了。 @OpportunityLiu 
需要的话留邮箱。
![](http://ww2.sinaimg.cn/large/6c84b2d6gy1fg6nbvxqeij20kl0egwkh.jpg)

**Comment by OpportunityLiu** [comment]
liuzhengyuan13@outlook.com
有版本管理怕啥

**Comment by Mapaler** [comment]
就算是有版本管理也应该是可以删掉整个分支吧

**Comment by OpportunityLiu** [comment]
密码？
![image](https://cloud.githubusercontent.com/assets/13471233/26708854/ed34e5b0-4780-11e7-9519-477b97c00651.png)

**Comment by Mapaler** [comment]
没有密码啊

**Comment by OpportunityLiu** [comment]
那它在问我要什么？
直接回车不行啊

**Comment by OpportunityLiu** [comment]
难道不是你生成key的时候设了passpharse？

**Comment by Mapaler** [comment]
当然没设，刚才试了，有passpharse的用PuTTY Key Generator打开也需要输密码的，而我发给你的私钥可以直接打开的。

**Comment by Mapaler** [comment]
你试试用其他GUI？

**Comment by OpportunityLiu** [comment]
这一步就跪了。。。
https://help.github.com/articles/error-permission-denied-publickey/#check-that-you-are-connecting-to-the-correct-server

**Comment by OpportunityLiu** [comment]
装了2个GUI，看来我就是用网页版的命🙋

**Comment by Mapaler** [comment]
你以前用过ssh传git吗？会不会跟你以前的key冲突了？
我在Win下完全没问题

**Comment by Mapaler** [comment]
为什么你clone也需要输密码？

**Comment by Mapaler** [comment]
一直不成功吗？你试试先用https克隆到本地，然后再把url改成ssh加密钥呢？

**Comment by Mapaler** [comment]
@OpportunityLiu Are you OK?

**Comment by Mapaler** [comment]
你是去添加账户的Key了吗？我这个Key是项目专用的，不是你的账户的，你的账户没有项目权限用你的账户key也是不能编辑的。

**Comment by OpportunityLiu** [comment]
并没有，算了，我弃疗了

**Comment by OpportunityLiu** [comment]
不如直接在Collaborators 添加用户，还可以随时踢掉，多方便
反正都是可以编辑主项目的

**Comment by Mapaler** [comment]
那样需要一个一个去添加，其实我本来是想搞成把key公开下载，想用git的人可以自由使用不需要我专门去管的。

**Comment by Mapaler** [comment]
另外添加的合作者可以通过网页修改整个项目设置，而key只能用git管理代码。

**Comment by Mapaler** [comment]
https://github.com/Mapaler/EhTagTranslator/invitations
我已经邀请你了

**Comment by OpportunityLiu** [comment]
👍

**Comment by Mapaler** [comment]
为什么你最近的修改日志都是英文？

**Comment by OpportunityLiu** [comment]
因为我该用本地编辑就必须要写提交说明，又懒得切输入法

**Comment by Mapaler** [comment]
切输入法不就是一下shift么？
