### ISSUE TITLE
我就奇怪这几天Star的人怎么突然多了，原来是有人安利

### ISSUE THREAD

**Issue by Mapaler** [Mapaler/EhTagTranslator#24]
这几天Star的人突然多了4个，虽然绝对数量不多，但是环比上升非常明显，于是谷歌了下，找到了访客的来源。
https://bbs.white-plus.net/simple/index.php?t327877.html

**Comment by xioxin** [comment]
接下来就是着手翻译ui啦 最近沉迷小黄油

**Comment by xioxin** [comment]
突然发现我竟然是这个论坛的会员 2014年注册的 惊了
![image](https://user-images.githubusercontent.com/5716100/30303823-e7dc5cd4-972f-11e7-8b08-4fd713b65487.png)

**Comment by Mapaler** [comment]
你准备在主项目内写readme吗，我是准备把详细的readme转移到wiki里面去。首页只放简单的引导，那样说明就可以随便改而不影响主项目的文件数量了。

**Comment by jabsas** [comment]
emmm 那天刚好重新下了次chrome55 有些设置要重设次 就顺手安利了发  以前也蛮多人问来着

**Comment by xioxin** [comment]
可以 放两个版本的wiki入口 还有一份功能差异

**Comment by Mapaler** [comment]
我几天前写的你看到没有？
https://github.com/Mapaler/EhTagTranslator/wiki/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3

全放在wiki的document文件夹下，需要git拉取到本地才能看到文件夹。

**Comment by xioxin** [comment]
刚看见 话说 代码水平和主研发平台 去掉吧对于用户没有啥意义 😹

**Comment by xioxin** [comment]
我打算直接砍掉 输出css样式的功能 只保留内置的注入 

我是用不上这个功能 也不太清除有内置注入的情况输出css有啥用处

**Comment by xioxin** [comment]
![image](https://user-images.githubusercontent.com/5716100/30341397-7a9f76f6-97bb-11e7-8876-0a056bf3f338.png)
已经尝试对静态内容的替换

**Comment by xioxin** [comment]
![image](https://user-images.githubusercontent.com/5716100/30341482-c12455b0-97bb-11e7-98f7-8ec12556cf6c.png)
简单的实现了静态内容替换

**Comment by xioxin** [comment]
![image](https://user-images.githubusercontent.com/5716100/30343921-ca0d060a-97c4-11e7-8dc1-9e150dade82b.png)
看完苹果发布会了

**Comment by Mapaler** [comment]
当然可以去掉，反正两个脚本同时安装互相不冲突。还可以精简你的代码。
