### ISSUE TITLE
数据库增加外部链接字段

### ISSUE THREAD

**Issue by OpportunityLiu** [Mapaler/EhTagTranslator#29]
增加一个外部链接字段，使用 Markdown 语法保存一个或多个可选的 url
对于原作和角色，可以连接到对应的维基或萌百词条；
对于团队，可以连接到社团主页和公司页面；
对于艺术家，可以连接到对应的 P 站页面或微博；
对于恋物标签，可以连接到 EHWiki。

对于脚本而言，可以在“ Show Tag Definition”旁边添加一个“打开外部链接按钮”或直接替换此链接。

现有数据可以添加一个空字段。

- [x] 为旧数据增加空字段
- [x] 添加新的说明文档
- [x] 添加已经存在的艺术家链接
- [x] 在 `rows` 添加到数据库页面的链接
- [x] 更多后续维护
- [x] 脚本支持跟进

**Comment by xioxin** [comment]
是增加一列吗

**Comment by OpportunityLiu** [comment]
是这个意思

**Comment by Mapaler** [comment]
对于我的程序应该也没影响，我只获取前几个表格，到时候增加一列表格就行。

**Comment by OpportunityLiu** [comment]
改到 version 4 吧，只要不改动 tags 里的文件就好了

**Comment by Mapaler** [comment]
应用新版本后，保留老版本版本号获取一个月，之后再移除

**Comment by OpportunityLiu** [comment]
脚本都没啥问题了，下一步是支持打开外部链接

**Comment by xioxin** [comment]
最后一个格子应该不止放链接地址 应该放入md的链接格式 应该链接标题和地址

**Comment by OpportunityLiu** [comment]
可以

**Comment by Mapaler** [comment]
先规划做个样子看看吧，实际操作一下。其实我以前就有这个计划的，但是觉得可以直接写在介绍里，将来用JS实现的时候就能添加进去。

| 英文 | 中文 | 介绍 | 链接 |
| --- | --- | --- | --- |
| 英文 | 中文 | 介绍 | 链接 |

**Comment by OpportunityLiu** [comment]
数据库结构部分的更新完成。
后续需要增加数据和更新脚本。

**Comment by xioxin** [comment]
ETS已实现标签链接功能 
![image](https://user-images.githubusercontent.com/5716100/30484426-f4b118d8-99ef-11e7-90c6-418d0f311746.png)

**Comment by Mapaler** [comment]
如果这个链接很多怎么办，做个极端测试吧

**Comment by xioxin** [comment]
会自动换行 试过了
