### ISSUE TITLE
数据库版本信息表示方式变更

### ISSUE THREAD

**Issue by OpportunityLiu** [Mapaler/EhTagTranslator#30]
目前的表示方式有
1. `a[href='ETB_wiki-version']` @ `rows.md` （将在 version 5 弃用）
1. `a[href='wiki-version-number']` @ `wiki-version.md` （将在 version 5 弃用）
1. `a[title='wiki-version']` @ `wiki-version.md`（将在 version 5 弃用）
1. `a[title='database-structure-version']` @ `version.md`

之前的讨论 #23 
后续相关讨论请在此进行

**Comment by Mapaler** [comment]
你要改成atabase，那么wiki-version要不要换成结构版本（英文我不知道）

**Comment by OpportunityLiu** [comment]
`database-version` ? 好像不太对
要不直接 `version` @ `wiki-version.md` 或 `version` @ `version.md`

**Comment by Mapaler** [comment]
`database-structure-version@version.md`

怎么样

version.md放在根目录，将来万一还要添加其他东西的版本呢，这样获取这一个文件就能得到所有版本了。

**Comment by OpportunityLiu** [comment]
也可以

**Comment by OpportunityLiu** [comment]
version 4 什么时候应用

**Comment by Mapaler** [comment]
我回电脑上再检查一下

**Comment by Mapaler** [comment]
你现在同时存在database和tags两个文件夹，里面有相同的文件，那么在线编辑的时候算哪一个的？

**Comment by OpportunityLiu** [comment]
貌似因为 'd'<'t' 所以是 database

**Comment by OpportunityLiu** [comment]
😅

**Comment by Mapaler** [comment]
还是先不要database文件夹，这几个文件应该有唯一性。
等大家准备好后再进行迁移。

**Comment by Mapaler** [comment]
你要改就只能将tags文件夹改名，不要用复制，改了之后再改xinxon的程序。
版本更迭你搞得太快了，官方程序都失效了，

**Comment by Mapaler** [comment]
实际上版本5的所有东西都可以放在版本4，只不过版本更迭需要旧版本获取方式修改到新版本号后保留一个月，让旧程序使用者更新脚本后，再删除信息即可，不用更新版本。

**Comment by OpportunityLiu** [comment]
变更完毕

**Comment by xioxin** [comment]
所以现在最终文件夹名是什么

**Comment by OpportunityLiu** [comment]
数据库在 `database` 文件夹，版本信息在根目录下的 `version.md` 文件
@xioxin

**Comment by Mapaler** [comment]
我正在把我的脚本的一部分结构重写

**Comment by xioxin** [comment]
![image](https://user-images.githubusercontent.com/5716100/30479001-e3030306-99d8-11e7-9368-65cea59f507c.png)
链接解析已经搞定

**Comment by Mapaler** [comment]
我准备把介绍信息也搞成数组，不用html了，方便进一步生成其他的。
