### ISSUE TITLE
翻译缺失

### ISSUE THREAD

**Issue by mromm** [Mapaler/EhTagTranslator#31]
EhTagSyringe
![image](https://user-images.githubusercontent.com/10344393/32221806-ddff7a84-be71-11e7-907c-964e994888ee.png)
![image](https://user-images.githubusercontent.com/10344393/32222039-aec8fe56-be72-11e7-8afe-b4770505223f.png)
种子页面翻译缺失
![image](https://user-images.githubusercontent.com/10344393/32222160-278b2e22-be73-11e7-8f27-16a4e8be7d03.png)
收藏页面
![image](https://user-images.githubusercontent.com/10344393/32222190-42f0f35e-be73-11e7-9cba-404de000f260.png)
我的画廊页面
![image](https://user-images.githubusercontent.com/10344393/32222209-567fa4a6-be73-11e7-9ea0-805c442f5411.png)

**Comment by Mapaler** [comment]
@xioxin 找你的

**Comment by xioxin** [comment]
其实吧 因为最近有些忙 没翻译完 😂
