### ISSUE TITLE
Edge的Tampermonkey生成不了操作菜单。。。

### ISSUE THREAD

**Issue by ArisakaMashiro** [Mapaler/EhTagTranslator#32]
两个项目都是一样

**Comment by Mapaler** [comment]
Edge是个半成品，我网站的HTML5特性都显示不完，我们都没人去适配。

ETB本身在Edge运行没有问题，直接控制台执行ETB代码即可。可以正常生成CSS，但是CSS需要由Stylish扩展来实现显示，似乎Edge没有。
![image 5](https://user-images.githubusercontent.com/6565860/32956328-6f2f4884-cbf3-11e7-8f6f-978c4b004064.png)

经过测试，发现应该是Tampermonkey扩展BUG，github网站添加任何内容的脚本，都不运行，连个hellow world都没反应，原因我肯定不知道。

ETS必须用脚本扩展执行，所以没办法了，换真正的浏览器吧，我感觉Edge还不如IE好用。

**Comment by ArisakaMashiro** [comment]
FF和Vivaldi都有在用的，不过如果在win板上的话这些确实不如edge省电，对触摸的优化也差一些，无论如何，感谢回复

**Comment by Mapaler** [comment]
第一次听说Vivaldi，我在Surface触屏也一样使用火狐。

确实是没办法，你可以向Tampermonkey Edge版的作者反馈Github失效。

**Comment by OpportunityLiu** [comment]
GitHub 有 Content-Security-Policy 的，跨域脚本全被拦截了。

怎么想都是 Tampermonkey 的锅
