### ISSUE TITLE
EhTagTranslator脚本生成的css方面的问题

### ISSUE THREAD

**Issue by dodying** [Mapaler/EhTagTranslator#34]
由于`I"s`，导致整个样式出错，作者能转义一下吗
***
还有`font-size:0px;`希望能写成`font-size:0;`

**Comment by Mapaler** [comment]
`I''s`是什么？ETB 的话，你直接批量替换css里的文字就可以了，ETS需要联系作者。

**Comment by OpportunityLiu** [comment]
https://github.com/Mapaler/EhTagTranslator/wiki/parody/_compare/6e3b9764bc8135fd7dbfb97b07207de1a0e958ef...31c70be2df3fb135198c7fed59cc847592bc3440#diff-a744a8a8d32cd14798500220d5ebd59aR987
` | is | I"s | I"s（读音：Eyes，日文：アイズ）是日本知名漫画家桂正和的爱情漫画作品。自1997年（第19期）至2000年（第24期）间在少年Jump周刊上连载，并有发行单行本全套共15集。 | |`
就这个

**Comment by Mapaler** [comment]
还有没有其他需要转义的字符啊？

**Comment by xioxin** [comment]
我这边转换有问题吗 我看我的貌似可以正常显示

**Comment by Mapaler** [comment]
我的添加了一个字符的替换，你的我就不知道了。不过我测试的时候`I"S`也没问题

**Comment by dodying** [comment]
额，其实是使用Stylish可以保存，但报错
但使用Stylus报错而不能保存

额，还是用正则表达式替换吧，肯普法一条中有两个`"`

**Comment by Mapaler** [comment]
@dodying 我已经更新了，会自动在`"`前面加上`\`，但是需不需要在`\`前面加上`\`？以及其他可能需要转义的。
