### ISSUE TITLE
新的问题产生了

### ISSUE THREAD

**Issue by Mapaler** [Mapaler/EhTagTranslator#35]
由于页面太长了，不产生页面了，ETB出错。怎么办？
![image 4](https://user-images.githubusercontent.com/6565860/35634488-c30558ee-06e6-11e8-87fa-6461a3ee39c0.png)

恐怕得更改数据库的结构，甚至是模式了。
我个人觉得要适配原先的简易公开编辑，那么就得继续目前的Wiki表格编写模式。我提出的方法是：规定每个页面代码不能超过多少行，将长页面拆分成多个页面，由我们来负责监视，多的页面可以加入rows里面，rows增加一列“拆分序号”。

如果要改为其他代码模式，则需要找到一个方便公开编辑的渠道。

**Comment by OpportunityLiu** [comment]
不是吧。。。分页的话我的应用也要炸啊

**Comment by Mapaler** [comment]
你研究一下，想个办法吧，反正现在遇到了github页面的长度限制，我的是直接挂掉。@xioxin 的倒是没问题

**Comment by OpportunityLiu** [comment]
我这里暂时还没炸。

维持现在的结构的话只能拆了；
不过感觉最后还是要上真正的数据库啊，然后再搞个网页做编辑用的前端，用API给其他应用提供数据。。。

**Comment by Mapaler** [comment]
那谁做啊，还需要个专门的服务器

**Comment by Mapaler** [comment]
![image 18](https://user-images.githubusercontent.com/6565860/35659741-dc351fb4-0742-11e8-860a-06f279ea7def.png)
你对这一堆有没有了解，有没有哪个适合做纯文本编辑的，改成不转成表格的方式，这样就既可以公开编辑又可以直接读取了

**Comment by xioxin** [comment]
看看 https://imsun.github.io/gitment/
这是一个github page服务的评论系统 利用api操作Issues实现 

大概思路 利用page服务提供页面和表单

利用github api 进行编辑存储 至于数据存在哪里得看看文档有没有什么可以用的
https://developer.github.com/v3/

不一定靠谱

**Comment by xioxin** [comment]
现在可以先删减删减图片 来减少内容

**Comment by Mapaler** [comment]
那个要自己开发，工程量太大了。
再怎么删减图片也终有超过的那一天。

我觉得直接新增一套数据库格式，老版暂时保持能访问的原样不修改了。新的取消可视化，直接写成JSON，编辑也只能编辑JSON，就跟普通编辑代码一样了。

**Comment by xioxin** [comment]
编辑代码不太现实 容易出错

**Comment by Mapaler** [comment]
似乎这个根服务器有关系，md全部解析需要花很长时间，如果超时就不显示了。所以还是纯文本最简单了

**Comment by Mapaler** [comment]
怎么办，我是觉得直接用一个md代码块里写json纯文本的开发难度比较低。

**Comment by heroboy** [comment]
你不是有userscript吗，github自己不渲染，你可以在userscript里把md读出来渲染在页面上啊。

**Comment by Mapaler** [comment]
@heroboy ETS就是这样做的，我没必要重写一套吧。

**Comment by xioxin** [comment]
解析移植过去?

**Comment by xioxin** [comment]
可以找一个js的markdown转html的解析库 解析后 再走原来的解析

**Comment by Mapaler** [comment]
那还不如直接写MD解析了，还简单些

**Comment by OpportunityLiu** [comment]
好像可以了？

**Comment by xioxin** [comment]
什么可以了?

**Comment by OpportunityLiu** [comment]
这个问题自动消失了？我现在浏览那几个页面都没啥问题

**Comment by Mapaler** [comment]
不知道问题怎么出现的，现在暂时无法再现。

**Comment by OpportunityLiu** [comment]
那就出现了再reopen吧

**Comment by kayanouriko** [comment]
你们不准备搞个服务器么?
最近腾讯云打折,330元最多6年,个人开发够用了...
我准备把你们的Tag汉化数据迁移到我的服务器做api请求了...

**Comment by Mapaler** [comment]
毛线，这种东西你敢放国内？分分钟被关站。
我一开始就是准备用数据库做，但是后来考虑到维护成本问题才用GitHub的，这个更利于开放式管理。

**Comment by kayanouriko** [comment]
@Mapaler 机房是香港的,域名也是国外的,都不用备案,这不行?
也不展示,按你们上面讨论只提供api查询就好了...

**Comment by Mapaler** [comment]
我主要还是考虑到编辑的便捷性，自己做一套编辑系统太麻烦了。
