### ISSUE TITLE
徵求同意使用中文化翻譯的部分

### ISSUE THREAD

**Issue by DaidoujiChen** [Mapaler/EhTagTranslator#36]
Hello @Mapaler,

因為我個人的需要, 所以 build 了一個 service 是使用了這邊翻譯的部分, 如果覺得不妥的話, 我會把 source 的部分 private 起來, service 也會關掉, 感恩.

repo
[https://github.com/DaidoujiChen/htags](https://github.com/DaidoujiChen/htags)

**Comment by OpportunityLiu** [comment]
为什么不用 https://github.com/Mapaler/EhTagTranslator/wiki/EhTagBuilder 生成json，我看你那个有很多问题没处理啊

**Comment by DaidoujiChen** [comment]
@OpportunityLiu 

O口O" 真假, 因為我其實只想要 `英文名` -> `中文名` 的部分而已, 生成一個檔案之後也是包在 app 裡面而已, 不會每次調用, 不過 code 的部分是也還有想修的地方沒錯啦 =w="

**Comment by OpportunityLiu** [comment]
可是我还在每天努力更新啊

你也可以参考一下我的项目
https://github.com/OpportunityLiu/ExViewer/tree/master/EhTagTranslatorClient

**Comment by OpportunityLiu** [comment]
我看你那个主要两个问题
第一个是中间MARKDOWN没有处理，有的中文名是带图片的，比如 `kantai collection` 的中文是 `![大船](http://wx1.sinaimg.cn/large/6c84b2d6gy1fehdg37hq1g200k00c03b.gif)舰队Collection`
第二是不同的namespace中有英文名相同的条目，我看你那个合成同一个字典以后就只剩下一个了

EHTagBuilder 这些都是处理好的，因为它是基于渲染好的html而非markdown

**Comment by DaidoujiChen** [comment]
@OpportunityLiu 

蠔油, 感恩, 我再來研究一下

**Comment by Mapaler** [comment]
你既然懂json，而且也是不需要频繁更新的，就可以自己写一个转换程序把ETB生成json去掉介绍生成你需要的格式（其实直接在ETB设置里关掉生成简介和图片就行），这样你自己会节省很多精力，也不容易出错。

**Comment by DaidoujiChen** [comment]
@Mapaler 

也 3qq

**Comment by Mapaler** [comment]
@OpportunityLiu 你还看得懂Go语言啊，学过？我进去看了半天都看不懂

**Comment by OpportunityLiu** [comment]
@Mapaler 只是用了一下看了看返回结果

**Comment by Mapaler** [comment]
@OpportunityLiu 你是苹果手机啊

**Comment by OpportunityLiu** [comment]
`wget https://alltesthere-186305.appspot.com/`

**Comment by DaidoujiChen** [comment]
我也看不懂 javascript =w="

**Comment by DaidoujiChen** [comment]
目前我想吃掉 emoji 吃不掉就是了

**Comment by Mapaler** [comment]
什么叫吃掉emoji？不要emoji的话，ETB也可以关闭生成的啊

**Comment by xioxin** [comment]
干脆搞一套标准的json 丢到git目录下 定期更新一下

**Comment by Mapaler** [comment]
@xioxin 那样多半有人会直接用了，说都不说一声。

**Comment by xioxin** [comment]
@Mapaler  没差别的 该不说的还是不说的

**Comment by DaidoujiChen** [comment]
Hello @Mapaler & @xioxin 

我參考了 [這行](https://github.com/Mapaler/EhTagTranslator/blob/master/EhTagBuilder.user.js#L28)
然後用 [https://regex101.com/](https://regex101.com/) 這個網站測試

![2018-03-15 2 25 47](https://user-images.githubusercontent.com/670441/37447778-89340d38-285e-11e8-9a36-e943f08fbcba.png)

有些比如說像是

🧟‍♀️
🧟‍♂️

這種的就消不掉

簡單的像是

😄

就行

這邊我也會再試試看, 謝謝大家

**Comment by DaidoujiChen** [comment]
感謝 @OpportunityLiu & @xioxin 的想法

我直接讓 ci 噴一份檔案放到 s3 上面, 就不用每次去重新處理了, =w=

[https://s3-ap-northeast-1.amazonaws.com/daidouji-htags/htag.json](https://s3-ap-northeast-1.amazonaws.com/daidouji-htags/htag.json)

**Comment by xioxin** [comment]
@DaidoujiChen D 

这个正则可以过滤掉全部的表情
根据 http://www.unicode.org/Public/emoji/5.0/emoji-data.txt 整理

```
/\u{00A9}|\u{00AE}|\u{203C}|\u{2049}|\u{2122}|\u{2139}|[\u{2194}-\u{2199}]|[\u{21A9}-\u{21AA}]|[\u{231A}-\u{231B}]|\u{2328}|\u{23CF}|[\u{23E9}-\u{23F3}]|[\u{23F8}-\u{23FA}]|\u{24C2}|[\u{25AA}-\u{25AB}]|\u{25B6}|\u{25C0}|[\u{25FB}-\u{25FE}]|[\u{2600}-\u{2604}]|\u{260E}|\u{2611}|[\u{2614}-\u{2615}]|\u{2618}|\u{261D}|\u{2620}|[\u{2622}-\u{2623}]|\u{2626}|\u{262A}|[\u{262E}-\u{262F}]|[\u{2638}-\u{263A}]|\u{2640}|\u{2642}|[\u{2648}-\u{2653}]|\u{2660}|\u{2663}|[\u{2665}-\u{2666}]|\u{2668}|\u{267B}|\u{267F}|[\u{2692}-\u{2697}]|\u{2699}|[\u{269B}-\u{269C}]|[\u{26A0}-\u{26A1}]|[\u{26AA}-\u{26AB}]|[\u{26B0}-\u{26B1}]|[\u{26BD}-\u{26BE}]|[\u{26C4}-\u{26C5}]|\u{26C8}|\u{26CE}|\u{26CF}|\u{26D1}|[\u{26D3}-\u{26D4}]|[\u{26E9}-\u{26EA}]|[\u{26F0}-\u{26F5}]|[\u{26F7}-\u{26FA}]|\u{26FD}|\u{2702}|\u{2705}|[\u{2708}-\u{2709}]|[\u{270A}-\u{270B}]|[\u{270C}-\u{270D}]|\u{270F}|\u{2712}|\u{2714}|\u{2716}|\u{271D}|\u{2721}|\u{2728}|[\u{2733}-\u{2734}]|\u{2744}|\u{2747}|\u{274C}|\u{274E}|[\u{2753}-\u{2755}]|\u{2757}|[\u{2763}-\u{2764}]|[\u{2795}-\u{2797}]|\u{27A1}|\u{27B0}|\u{27BF}|[\u{2934}-\u{2935}]|[\u{2B05}-\u{2B07}]|[\u{2B1B}-\u{2B1C}]|\u{2B50}|\u{2B55}|\u{3030}|\u{303D}|\u{3297}|\u{3299}|\u{1F004}|\u{1F0CF}|[\u{1F170}-\u{1F171}]|\u{1F17E}|\u{1F17F}|\u{1F18E}|[\u{1F191}-\u{1F19A}]|[\u{1F1E6}-\u{1F1FF}]|[\u{1F201}-\u{1F202}]|\u{1F21A}|\u{1F22F}|[\u{1F232}-\u{1F23A}]|[\u{1F250}-\u{1F251}]|[\u{1F300}-\u{1F320}]|\u{1F321}|[\u{1F324}-\u{1F32C}]|[\u{1F32D}-\u{1F32F}]|[\u{1F330}-\u{1F335}]|\u{1F336}|[\u{1F337}-\u{1F37C}]|\u{1F37D}|[\u{1F37E}-\u{1F37F}]|[\u{1F380}-\u{1F393}]|[\u{1F396}-\u{1F397}]|[\u{1F399}-\u{1F39B}]|[\u{1F39E}-\u{1F39F}]|[\u{1F3A0}-\u{1F3C4}]|\u{1F3C5}|[\u{1F3C6}-\u{1F3CA}]|[\u{1F3CB}-\u{1F3CE}]|[\u{1F3CF}-\u{1F3D3}]|[\u{1F3D4}-\u{1F3DF}]|[\u{1F3E0}-\u{1F3F0}]|[\u{1F3F3}-\u{1F3F5}]|\u{1F3F7}|[\u{1F3F8}-\u{1F3FF}]|[\u{1F400}-\u{1F43E}]|\u{1F43F}|\u{1F440}|\u{1F441}|[\u{1F442}-\u{1F4F7}]|\u{1F4F8}|[\u{1F4F9}-\u{1F4FC}]|\u{1F4FD}|\u{1F4FF}|[\u{1F500}-\u{1F53D}]|[\u{1F549}-\u{1F54A}]|[\u{1F54B}-\u{1F54E}]|[\u{1F550}-\u{1F567}]|[\u{1F56F}-\u{1F570}]|[\u{1F573}-\u{1F579}]|\u{1F57A}|\u{1F587}|[\u{1F58A}-\u{1F58D}]|\u{1F590}|[\u{1F595}-\u{1F596}]|\u{1F5A4}|\u{1F5A5}|\u{1F5A8}|[\u{1F5B1}-\u{1F5B2}]|\u{1F5BC}|[\u{1F5C2}-\u{1F5C4}]|[\u{1F5D1}-\u{1F5D3}]|[\u{1F5DC}-\u{1F5DE}]|\u{1F5E1}|\u{1F5E3}|\u{1F5E8}|\u{1F5EF}|\u{1F5F3}|\u{1F5FA}|[\u{1F5FB}-\u{1F5FF}]|\u{1F600}|[\u{1F601}-\u{1F610}]|\u{1F611}|[\u{1F612}-\u{1F614}]|\u{1F615}|\u{1F616}|\u{1F617}|\u{1F618}|\u{1F619}|\u{1F61A}|\u{1F61B}|[\u{1F61C}-\u{1F61E}]|\u{1F61F}|[\u{1F620}-\u{1F625}]|[\u{1F626}-\u{1F627}]|[\u{1F628}-\u{1F62B}]|\u{1F62C}|\u{1F62D}|[\u{1F62E}-\u{1F62F}]|[\u{1F630}-\u{1F633}]|\u{1F634}|[\u{1F635}-\u{1F640}]|[\u{1F641}-\u{1F642}]|[\u{1F643}-\u{1F644}]|[\u{1F645}-\u{1F64F}]|[\u{1F680}-\u{1F6C5}]|[\u{1F6CB}-\u{1F6CF}]|\u{1F6D0}|[\u{1F6D1}-\u{1F6D2}]|[\u{1F6E0}-\u{1F6E5}]|\u{1F6E9}|[\u{1F6EB}-\u{1F6EC}]|\u{1F6F0}|\u{1F6F3}|[\u{1F6F4}-\u{1F6F6}]|[\u{1F6F7}-\u{1F6F8}]|[\u{1F910}-\u{1F918}]|[\u{1F919}-\u{1F91E}]|\u{1F91F}|[\u{1F920}-\u{1F927}]|[\u{1F928}-\u{1F92F}]|\u{1F930}|[\u{1F931}-\u{1F932}]|[\u{1F933}-\u{1F93A}]|[\u{1F93C}-\u{1F93E}]|[\u{1F940}-\u{1F945}]|[\u{1F947}-\u{1F94B}]|\u{1F94C}|[\u{1F950}-\u{1F95E}]|[\u{1F95F}-\u{1F96B}]|[\u{1F980}-\u{1F984}]|[\u{1F985}-\u{1F991}]|[\u{1F992}-\u{1F997}]|\u{1F9C0}|[\u{1F9D0}-\u{1F9E6}]/gu
```

**Comment by Mapaler** [comment]
不知道是不是属于新版的Unicode里添加的emoji，这个正则xioxin也写了有一年了吧。不过我们的数据库里有这些Emoji吗？

**Comment by DaidoujiChen** [comment]
@Mapaler 

有耶 剛剛那個就是 `zombie` 裡面的 還分男生女生 =w="

**Comment by Mapaler** [comment]
![image 7](https://user-images.githubusercontent.com/6565860/37450083-948d04a6-2867-11e8-9ff3-992c8843cc81.png)
我刚才用我的程序试了一下，是可以匹配这两个emoji的，你应该是用法不对吧。

**Comment by DaidoujiChen** [comment]
@Mapaler 

嗯 真的 可能是我手殘複製錯了, 不過還是刪不掉後面的那個 `♀️` & `♂️`
剛剛 @xioxin 貼的那個可以消的很乾淨說, 不過他好像刪掉了 OoO

**Comment by Mapaler** [comment]
你自己加上♀️ 和 ♂️不就行了吗，这两个能算Emoji吗？

**Comment by DaidoujiChen** [comment]
@Mapaler 

我也不知道 哈哈

**Comment by DaidoujiChen** [comment]
感謝大家 那我就自己 close 掉這個 issue 囉 >w<

**Comment by OpportunityLiu** [comment]
@DaidoujiChen 

数据库已经迁移到
https://github.com/EhTagTranslation/Database/

现在有持续集成发布的json版本了
https://github.com/EhTagTranslation/Database/releases

开发文档
https://github.com/EhTagTranslation/Database/wiki/%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97

后续这边的数据不会再更新了，如果你方便的话，可以考虑迁移过去。
