### ISSUE TITLE
没有出现顶部操作菜单

### ISSUE THREAD

**Issue by sunyink** [Mapaler/EhTagTranslator#38]
奇怪，说明图片中的位置那个位置是空的。没地更新，去e网站也都是英文。
Chrome + Tampermonkey 使用，我先试了注射器，后又试了构建者，都不行；T插件图标显示2个脚本都启用的。

.....甚至去flag里开实验性了，最后也没出现。

**Comment by sunyink** [comment]
更新了chrome，原来的48不行。  挺怀念48的UI。

**Comment by Mapaler** [comment]
ETB在48都不行的吗，48没那么老吧？IE11都支持ETB脚本的（只是没插件来自动运行）。要不试试火狐吧，看看火狐的界面？你喜欢Chrome内核的话也可以试试Vivaldi浏览器。
