### ISSUE TITLE
和E-Hentai Downloader脚本一起运行，后者会缺少一个GP信息

### ISSUE THREAD

**Issue by sunyink** [Mapaler/EhTagTranslator#39]
和E-Hentai    Downloader脚本一起运行，Downloader下载脚本将没法显示若下载当前本子将消耗多少GP信息。不太不方便，不知能不能好。

原文本就是这个：“ | Estimated Limits Cost: *"

又及，下载窗也弹不出了。

**Comment by Mapaler** [comment]
哪个脚本会出现，ETS还是ETB？

**Comment by sunyink** [comment]
ets,EhTagSyringe.1.1.11
对方脚本是1.29.1，chrome65

**Comment by sunyink** [comment]
哦，下午好。我后来也去E-Hentai Downloader的github讨论了下。他提到Downloader脚本若顺序靠后则会读错网页。但EhTagSyringe又有”document-start“的属性，所以肯定比Downloader脚本先工作，于是出现了此问题。在Tampermonkey里手动设置了ETS→”document-end“，目前试了试可以一起工作了。

**Comment by Mapaler** [comment]
这个问题还是@xioxin
