### ISSUE TITLE
关于检查CSS文件更新

### ISSUE THREAD

**Issue by dodying** [Mapaler/EhTagTranslator#4]
突然发现Stylish里有“查找更新”的选项，作者大大可以定时（比如每天或每周）把生成的css文件上传
推荐文件版本：1.纯翻译版（无简介、图片） 2.简介版（有简介、无图片） 3.延伸版（有简介、有图片）

**Comment by Mapaler** [comment]
必须是传到userstyles.org的才支持，跟油猴一样的道理。
现在数据库核心的female tag还不足，还不足以传。
而且那样会打消别人添加Tag的积极性吧，毕竟不是即时更新的？

**Comment by dodying** [comment]
额，那算了，还是老老实实的复制粘帖吧

**Comment by Mapaler** [comment]
没必要更新那么快吧，一次多找些没有翻译的Tag，搞完了文字汉化再慢慢去搞图片。

另外可以在Issues里编辑新的，避免跟别人同时编辑丢失数据，最后做完了再拷过去。

**Comment by Mapaler** [comment]
另外也可以用Git拉到本地修改（Wiki右边栏底部有链接），不过我还没碰到推送发生冲突的，不知道怎么解决。

**Comment by dodying** [comment]
Git什么的完全不会用，我只是兴趣爱好
我还是直接编辑吧
