### ISSUE TITLE
这个脚本会与熊猫书签不兼容，如果能够改进一下就太好了

### ISSUE THREAD

**Issue by MNK-S** [Mapaler/EhTagTranslator#41]
开启这个脚本后，无法使用熊猫书签的“列表模式”功能，希望能够改进一下
熊猫书签地址：https://loligit.github.io/panda/

**Comment by Mapaler** [comment]
这东西拿来干啥的

**Comment by MNK-S** [comment]
将图片加载为列表，比较方便看和下载

**Comment by Mapaler** [comment]
![2](https://user-images.githubusercontent.com/6565860/39377414-9f41ebf4-4a87-11e8-911d-103973916602.png)

![1](https://user-images.githubusercontent.com/6565860/39377375-7e581bc0-4a87-11e8-9c8e-90920a0fdebf.png)
不是官方就支持这个功能么

**Comment by OpportunityLiu** [comment]
毕竟巨贵的Perk

来打个广告
https://github.com/OpportunityLiu/ExViewer

**Comment by Mapaler** [comment]
我都用掉几百p了

**Comment by MNK-S** [comment]
P太贵了.........应该是把它的弹出窗口拦截了的原因

**Comment by Mapaler** [comment]
你可以试试ETB生成CSS，那个应该不会影响其他的脚本

**Comment by Mapaler** [comment]
刚才发现VPS上的H@H脚本居然没有运行，我有多长一段时间没得Hath收入了。

目前我只换了这些
![_2018-05-12t14-27-34 267z](https://user-images.githubusercontent.com/6565860/39958314-e95a6bb4-5633-11e8-877e-455eab0f8792.png)

似乎资产不是很多？不过这些到底能拿来干嘛？
![12](https://user-images.githubusercontent.com/6565860/39958354-7b22a2be-5634-11e8-9781-2a9144ab10b4.png)

**Comment by Mapaler** [comment]
![13](https://user-images.githubusercontent.com/6565860/39958434-5877421e-5635-11e8-99b0-3a54ce986a7a.png)
刚才试着卖了1HATH，还是看不懂这些啊
