### ISSUE TITLE
EhTagSyringe加载失败

### ISSUE THREAD

**Issue by robertpb** [Mapaler/EhTagTranslator#42]
Windows 10 1803，Chrome版本68.0.3440.106，TamperMonkey 4.7，打开E站以及本GitHub页面时TamperMonkey显示有脚本加载，但页面无任何变化
![image](https://user-images.githubusercontent.com/6861049/43898673-279c4fd6-9c12-11e8-967d-7e22e7787195.png)

**Comment by xioxin** [comment]
尝试刷新页面

**Comment by xioxin** [comment]
右键审查元素 看有没有报错信息
![image](https://user-images.githubusercontent.com/5716100/43900551-cea68300-9c17-11e8-9ed9-5d5acf488a2a.png)

**Comment by robertpb** [comment]
昨天重启了也没用，今天就自己好了。。真实玄学
打扰了

**Comment by YuZ-G** [comment]
有报错怎么办啊？

**Comment by xioxin** [comment]
@YuZ-G  开一个新的Issues 说明下浏览器版本 什么状况 有错误信息附上错误内容
