### ISSUE TITLE
无法加载数据库-github页面上没有显示菜单

### ISSUE THREAD

**Issue by gowinder** [Mapaler/EhTagTranslator#44]
firefox 61.0.2 x64
暴力猴 2.9.5
脚本版本  
    1.1.12

控制台报错
Content Security Policy: 页面设置阻止读取位于 self 的一项资源("script-src")。 Source: !function e(a){var b=document.querySelec....
已拦截跨源请求：同源策略禁止读取位于 https://api.github.com/_private/browser/stats 的远程资源。（原因：CORS 请求未能成功）。

**Comment by Mapaler** [comment]
换扩展

**Comment by gowinder** [comment]
解决了，在firefox  的设置页面，about:config
把 security.csp.enable  设置成false就有了，更新完成后再改成true

**Comment by Mapaler** [comment]
不建议这样做，又安全风险，换那个T什么monkey扩展就好了，我记不得单词。

**Comment by xioxin** [comment]
Tampermonkey
