### ISSUE TITLE
小建议：tag翻译最好增加同时显示原文的功能

### ISSUE THREAD

**Issue by oufumihiko** [Mapaler/EhTagTranslator#46]
RT

**Comment by Mapaler** [comment]
ETS可以在面板里随时切换到原文。
@xioxin 如果需要同时显示原文，是不是修改CSS模板，把原文显示出来就行了？但是没有伪元素来添加括号了。

**Comment by Mapaler** [comment]
@xioxin 看到改动了，还行，不过做成两个独立复选框，当选中第一个的时候选第二个就没意义。不如做成三个单选框，或者选中第二个的时候自动取消第一个？

**Comment by Mapaler** [comment]
![screenshot 2018-10-23 14 03 25](https://user-images.githubusercontent.com/6565860/47339010-70dcef80-d6cc-11e8-847c-b18c3a5925bb.png)
研究了半天，还是没法让a:focus时的::after显示在其他div上面

**Comment by xioxin** [comment]
我这里并不存在这个问题 你什么浏览器？

**Comment by xioxin** [comment]
哦理解了 你打算吧选中样式 包含到英文

**Comment by xioxin** [comment]
功能已经实现


| 临时切换 | 永久切换 |
|:---------:|:--------:|
| ![image](https://user-images.githubusercontent.com/5716100/47340048-a59e7600-d6cf-11e8-9d96-ec4fb2957ab7.png) | ![image](https://user-images.githubusercontent.com/5716100/47340062-b51dbf00-d6cf-11e8-9488-75389954319c.png) |

样式上还有一些瑕疵，因为工作比较忙没啥时间 所以这些细节以后有时间再优化
![image](https://user-images.githubusercontent.com/5716100/47340230-22315480-d6d0-11e8-930e-1145935f8a93.png)

**Comment by Mapaler** [comment]
@xioxin 那是我自己修改的啦，我开始是想实现中英放到同一个标签下，但是后来发现after始终在元素上方码查询后发现需要把after设为负数才可以。可是设为负数的过程中，父级div又显示到了上方，现在在解决这个问题。

**Comment by xioxin** [comment]
吧你现在的样式分享一下 我看看问题出在哪里

**Comment by Mapaler** [comment]
我整理一下思路
* 如果需要after显示在原dom下方，需要以相对位置，设置z-index为负数。  
https://blog.csdn.net/weixin_40672882/article/details/81184145
* 如果以相对位置来定义伪元素，那么focus和hover的层级就需要使用父级元素的z-index来区别。
* 父级a如果设置了index那么就无法让背景显示在after上方，只能让文字内容显示在上方。
* 如果不给a设置index，给div设置index，会因为div不存在foucus而让鼠标离开按钮时伪元素显示到其他的下面。
