### ISSUE TITLE
导入样式出错了。。

### ISSUE THREAD

**Issue by Landius** [Mapaler/EhTagTranslator#48]
这几行都是同一个问题，我用的`Chromium 70.0.3538.110`+`violent monkey`+`stylus`

![1](https://user-images.githubusercontent.com/11910028/51451137-d180d480-1d6e-11e9-8b23-f28862664b33.png)
![2](https://user-images.githubusercontent.com/11910028/51451139-d3e32e80-1d6e-11e9-86c4-8205183fbaf0.png)

**Comment by Mapaler** [comment]
https://github.com/Mapaler/EhTagTranslator/commit/bffc19e59488078ef3f40fc12468917f13ebd90f
ETB已修复，感谢。

**Comment by Mapaler** [comment]
因为很久没用ETB了，都没发现出现了问题。原因是体换时没有替换全部引号，只替换了第一个。
