### ISSUE TITLE
水楼 2代

### ISSUE THREAD

**Issue by OpportunityLiu** [Mapaler/EhTagTranslator#49]

**Comment by Mapaler** [comment]
新年快乐

**Comment by OpportunityLiu** [comment]
新年快乐

**Comment by xioxin** [comment]
新年快乐

**Comment by Mapaler** [comment]
我居然到现在都没买NS

**Comment by xioxin** [comment]
你居然到现在都没买NS

**Comment by Mapaler** [comment]
你买了这么多东西？
我到现在连信用卡都还不起，别说主机了

**Comment by Mapaler** [comment]
![Screenshot 2019-03-15 15 01 18](https://user-images.githubusercontent.com/6565860/54414194-4949fa80-4733-11e9-92e9-76450caf4740.png)
为什么变化这么多？

**Comment by OpportunityLiu** [comment]
把规格化的那部分更改merge 进去了

**Comment by ra1nbow2000** [comment]
昨天清除了一次浏览器数据（包括cookie）后，发现插件失效了，具体表现为点击ehtag按钮后菜单不出来了，且网站没有发生任何变化，只有网址栏后面多了一个“#”，已经试过了重装，重启油猴，禁用其他所有插件，重启浏览器，均没有作用，不知道是不是只有我遇到这种情况

**Comment by OpportunityLiu** [comment]
网站已然改版 @xioxin

**Comment by Mapaler** [comment]
哪个网站改版了？

**Comment by OpportunityLiu** [comment]
e站啊

**Comment by xioxin** [comment]
发现了 第三方app也都失效了

**Comment by OpportunityLiu** [comment]
这次动作挺大的，上次都是去年7月的事了。

不过感觉反而变丑了。

**Comment by OpportunityLiu** [comment]
@Mapaler male和female还是按wiki顺序走吧，不然添加新标签的时候就彻底乱了

**Comment by Mapaler** [comment]
我不知道哪里有顺序

**Comment by Mapaler** [comment]
缩略图是全部统一用手机版域名吗，那我就把辅助器修改一下。

**Comment by OpportunityLiu** [comment]
https://ehwiki.org/wiki/Fetish_Listing 按这个顺序，基本上是先根据类别分大类小类，然后字母顺序

我这面改一下吧，刚测了下速，还是ehgt.org快一点

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/55717148-476e1100-5a2b-11e9-8c12-c77d512550f3.png)
![图片](https://user-images.githubusercontent.com/13471233/55717155-4b9a2e80-5a2b-11e9-9b2b-ebb971f7aa76.png)

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/55718786-2e675f00-5a2f-11e9-91fa-3adc52766a8b.png)
剩下那个基本全部超时

**Comment by Mapaler** [comment]
因为exhentai需要cookies吧

**Comment by OpportunityLiu** [comment]
因为被墙，不然那些连上的怎么解释

**Comment by Mapaler** [comment]
为什么ETS每次更新了数据库后刷新还是有New在飘？需要手动点一次“立即检查”才能取消。更新数据时没有储存新的hash吗？

**Comment by Mapaler** [comment]
@xioxin 要怎么做才能把Material Icons给内置呢？直接把字体文件给缓存下来，怎么用到代码里。不知道如何获取缓存的url

**Comment by Mapaler** [comment]
![Screenshot 2019-04-11 18 44 05](https://user-images.githubusercontent.com/6565860/55951440-d6786480-5c89-11e9-8558-f3499684eec1.png)
![Screenshot 2019-04-11 18 44 18](https://user-images.githubusercontent.com/6565860/55951441-d6786480-5c89-11e9-9554-d75995df2675.png)
经典98风

**Comment by Mapaler** [comment]
![Screenshot 2019-04-11 20 53 09](https://user-images.githubusercontent.com/6565860/55958674-d719f680-5c9b-11e9-991b-6fcdba2ba1fc.png)
想要能调整大小就不能显示内容了，真是个麻烦事。

**Comment by Mapaler** [comment]
![Screenshot 2019-04-11 22 37 57](https://user-images.githubusercontent.com/6565860/55966162-7940db00-5caa-11e9-87f6-398753d9b8b9.png)
做好了透明度调整，明天再看看下面的输入框怎么弄

**Comment by Mapaler** [comment]
![Screenshot 2019-04-12 16 40 35](https://user-images.githubusercontent.com/6565860/56024096-ea7f9d00-5d41-11e9-970a-33ac6c3a0cab.png)
看起来完成了，懒得做设置储存了。

**Comment by Mapaler** [comment]
![Screenshot 2019-04-12 18 47 27](https://user-images.githubusercontent.com/6565860/56031962-70f0aa80-5d53-11e9-85b7-e4febbdd093e.png)
@OpportunityLiu wiki内的锚链似乎都失效了，怎么回事？

**Comment by OpportunityLiu** [comment]
@Mapaler 就不能顺手把male也加上

**Comment by Mapaler** [comment]
没有搜男的习惯

**Comment by OpportunityLiu** [comment]
@Mapaler 
![图片](https://user-images.githubusercontent.com/13471233/56077284-f3897080-5e0c-11e9-9553-3b66b2c5299f.png)
没啥问题啊？

**Comment by Mapaler** [comment]
@OpportunityLiu 我之前点了锚链不会跳下去

**Comment by Mapaler** [comment]
![QQ图片20190420005324](https://user-images.githubusercontent.com/6565860/56453045-ecfb7b80-636d-11e9-80a8-d1ebc4a6640c.jpg)
买了NS主机，下一步
先要买什么呢

**Comment by xioxin** [comment]
最新的系统有中文的
第一推荐肯定是《塞尔达荒野之息》

**Comment by Mapaler** [comment]
安卓可以控制新加的用户的数据吗

我可以在主用户打开usb调试，用adb backup备份/restore恢复，但是新增的用户无法使用开发者工具，是不是不root的话所有的数据就是不可以修改的？

**Comment by Mapaler** [comment]
塞尔达是毒瘤，昨晚玩了一个通宵。

**Comment by xioxin** [comment]
加下ns好友啊 SW-2527-1381-7808

发自我的 iPhone

**Comment by Mapaler** [comment]
我暂时还没开会员，目前暂时没联网需求。

**Comment by Mapaler** [comment]
Github给我发了好多邮件啊，为什么会这么多需要改项目的东西？
@OpportunityLiu

**Comment by OpportunityLiu** [comment]
@Mapaler 啥时候？昨天吗，昨天配了下 Editor 的持续集成

**Comment by Mapaler** [comment]
什么是持续集成？ Editor需要一直修改吗？
![Screenshot 2019-04-24 16 42 16](https://user-images.githubusercontent.com/6565860/56645295-fe1af400-66af-11e9-9d38-b397b41ee8cd.png)

**Comment by xioxin** [comment]
代码编译

发自我的 iPhone

**Comment by OpportunityLiu** [comment]
@Mapaler 就是我的代码push上去以后，程序自动编译并发布
EhTagTranslation/Database 会自动发布新的release
EhTagTranslation/Editor 会自动生成发布到 gh-pages 分支
EhTagTranslation/EhTagConnector 会自动生成发布到 Azure

**Comment by Mapaler** [comment]
为什么脚本语言还需要编译的呢，编译出来不还是脚本语言吗？
难道作用是将用到的库部分写入成品脚本中？

**Comment by OpportunityLiu** [comment]
@Mapaler 可是TS也不能直接在浏览器跑啊

**Comment by OpportunityLiu** [comment]
@Mapaler 最近口味变重了？
也在 https://ehtagtranslation.github.io/Editor 提交一份试用一下呗

**Comment by Mapaler** [comment]
我只是在玩 https://github.com/Mapaler/EhTagTranslator/wiki/ETTWikiHelper#%E6%A0%87%E7%AD%BE%E7%BC%96%E8%BE%91%E5%B7%A5%E5%85%B7 这个，添加的过程中发现一些不知道是什么意思的，于是在修订

**Comment by OpportunityLiu** [comment]
现在可以直接粘贴了

![1](https://user-images.githubusercontent.com/13471233/56876161-0d1af100-6a78-11e9-94ca-7ed642acf86a.gif)

**Comment by Mapaler** [comment]
不是很懂你的意思，就是直接粘贴富文本，自动转换成MD吗？
***
我玩的是下面的标签辅助程序，不是缩略图辅助程序。那个页面有两个。

**Comment by OpportunityLiu** [comment]
是，可以直接复制粘贴网页

**Comment by Mapaler** [comment]
* 这个必填星号为什么不是content，是有实体的呢？
![Screenshot 2019-04-29 16 14 17](https://user-images.githubusercontent.com/6565860/56883783-47958580-6a9a-11e9-846b-53daa44a1ab9.png)
* 粘贴富文本功能导致了连Ctrl+Z都不能用，我觉得问题比较严重，不小心删多了都救不回来。
***
![Screenshot 2019-04-29 16 14 34](https://user-images.githubusercontent.com/6565860/56883893-9e9b5a80-6a9a-11e9-8ae2-a8f39ab74760.png)
提交之后不会返回，需要加一个返回按钮。另外提交后，在没有内容修改的情况下，提交按钮变为灰色不可用比较好。
其他我觉得可以考虑添加的你自己看着办。

**Comment by OpportunityLiu** [comment]
>     * 这个必填星号为什么不是content，是有实体的呢？

框架说了算，我只是写了required
![图片](https://user-images.githubusercontent.com/13471233/56884933-c809b580-6a9d-11e9-8afd-bc36efe8985a.png)


>     * 粘贴富文本功能导致了连Ctrl+Z都不能用，我觉得问题比较严重，不小心删多了都救不回来。

好像跟富文本粘贴没啥关系，我再看看

> 提交之后不会返回，需要加一个返回按钮。

可以直接浏览器点后退，而且其实返回的意义不是很大，一般从e站直接跳过来编辑完回e站。
会加上。

> 另外提交后，在没有内容修改的情况下，提交按钮变为灰色不可用比较好。

提交前都可以，问题是没办法确认手里的这份是不是最新的，只有提交才知道没修改

**Comment by OpportunityLiu** [comment]
> 提交之后不会返回，需要加一个返回按钮

顺便，点 header 上的`Ehtag Editor` 也会到列表页

**Comment by OpportunityLiu** [comment]
> > ```
> > * 粘贴富文本功能导致了连Ctrl+Z都不能用，我觉得问题比较严重，不小心删多了都救不回来。
> > ```
> 
> 
> 好像跟富文本粘贴没啥关系，我再看看

是设了AutoResize才无法撤销的。。。

**Comment by OpportunityLiu** [comment]
搞不来，就这样吧

**Comment by OpportunityLiu** [comment]
@Mapaler 其他的都改好了，撤销那个没救

**Comment by Mapaler** [comment]
那你把AutoResize关掉也好啊，上面的英文名输入框就能撤销的。不能撤销问题太大了。

**Comment by Mapaler** [comment]
我到现在都不是很理解这种单页应用/框架，正常人都会觉得后退会回到上一个网页。点标题我都是找了半天才发现的，所以后退还是有必要。

我说的无修改变灰，只是说当前页面数据没有修改时变灰，不然好几次我点了提交后不知道提交成功没有，就又点了一下。
比如你可以点了提交，先变灰，然后根据返回的正确或错误，变为红色叉或绿色勾。如果修改了页面数据，就又重新变回“提交”。

**Comment by Mapaler** [comment]
我觉得是在很有必要做一个editer的使用说明，而不只是书写格式的说明

**Comment by OpportunityLiu** [comment]
> 我说的无修改变灰，只是说当前页面数据没有修改时变灰，不然好几次我点了提交后不知道提交成功没有，就又点了一下。
> 比如你可以点了提交，先变灰，然后根据返回的正确或错误，变为红色叉或绿色勾。如果修改了页面数据，就又重新变回“提交”。

提示是有的，你说那个有点复杂了，不过未修改情况下不能提交加上了。


> 我觉得是在很有必要做一个editer的使用说明，而不只是书写格式的说明

Issue开了，有空写

> 那你把AutoResize关掉也好啊，上面的英文名输入框就能撤销的。不能撤销问题太大了。

这个还是完了整个完善的功能出来把，现在先这样。
没有autosize我受不了

**Comment by chocolatl** [comment]
low lolicon | 未通过萝莉 | 表示萝莉(lolicon)的情况没有通过存在规则(presence rule)。需要萝莉(lolicon)标签。
-- | -- | --

这个条目的翻译是不是有点迷，看了下EHWiki应该是指画廊含有少量萝莉标签的图片吧，我不太确定
@Mapaler

**Comment by OpportunityLiu** [comment]
尬翻译很多，关键你要提出一个更好的方案

**Comment by chocolatl** [comment]
> 尬翻译很多，关键你要提出一个更好的方案

感觉按EHWiki直译就会难以理解，但是翻译偏离EHWiki太多感觉也不好

**Comment by chocolatl** [comment]
另外我想问一下标签来源是哪里，是<https://e-hentai.org/tools.php?act=taggroup>吗，我粗略对照了一下标签数量，感觉对不上，翻译这边的标签数量貌似更多

**Comment by OpportunityLiu** [comment]
ehwiki有整理好的列表 https://ehwiki.org/wiki/Fetish_Listing

**Comment by chocolatl** [comment]
> ehwiki有整理好的列表 https://ehwiki.org/wiki/Fetish_Listing

中文数据库是按artist、female...来分类的，Fetish Listing也没有包含全部标签，应该还有其它的来源

**Comment by OpportunityLiu** [comment]
其他来源就是刷e站

**Comment by DiamondYuan** [comment]
> 其他来源就是刷e站

有什么办法可以比较方便的获取结构化数据么？

**Comment by OpportunityLiu** [comment]
在 https://github.com/EhTagTranslation/Database 这边有，现在是两边同步的，之后应该会迁移过去

**Comment by DiamondYuan** [comment]
> 在 https://github.com/EhTagTranslation/Database 这边有，现在是两边同步的，之后应该会迁移过去

源数据可以用 json 。然后可以通过 json 来生成预览网站和 markdown。

本来我想开发一个 web服务 写一个类似 wiki 的。这下省事了。

**Comment by OpportunityLiu** [comment]
预览和编辑你可以参考这边 https://ehtagtranslation.github.io/Editor/list/all

**Comment by OpportunityLiu** [comment]
东西都有，就是懒得写文档:stuck_out_tongue_closed_eyes:

**Comment by DiamondYuan** [comment]
> 东西都有，就是懒得写文档😝

为什么很多图都挂了。以及 JSON 需要我自己转换么？

**Comment by chocolatl** [comment]
挂的图是故意的吧，因为露点了

**Comment by DiamondYuan** [comment]
你们有兴趣一起开发本地漫画管理软件么。 QAQ

**Comment by OpportunityLiu** [comment]
你用的ts话看这个就行了https://github.com/EhTagTranslation/Database/blob/master/tools/interface.d.ts

**Comment by OpportunityLiu** [comment]
markdown那里nswf图的链接是写在title而非alt里的，生成的JSON里面这些都是处理好的

**Comment by OpportunityLiu** [comment]
有渲染成HTML的版本和纯文字版本
https://github.com/EhTagTranslation/Database/wiki/%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97

**Comment by DiamondYuan** [comment]
> 有渲染成HTML的版本和纯文字版本
> https://github.com/EhTagTranslation/Database/wiki/%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97

研究了一下，太厉害了。可以少做很多事情了。

**Comment by DiamondYuan** [comment]
> 有渲染成HTML的版本和纯文字版本
> https://github.com/EhTagTranslation/Database/wiki/%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97

要不要考虑把数据发一份到 npm 上面，配合持续集成。
提供 js 和 ts 的 api。

**Comment by Mapaler** [comment]
![图像 3](https://user-images.githubusercontent.com/6565860/58751499-d3ebfb80-84d1-11e9-941d-67f1bd367907.png)
@OpportunityLiu  可以给这里加个Title吗？

**Comment by chocolatl** [comment]
这个标签编辑器的提交是怎样做到的，好神奇啊

**Comment by OpportunityLiu** [comment]
发请求给azure service，服务器端再修改内容并push到GitHub，最后持续集成生成发布文件，网页这面才会更新。。。

一圈下来实际要一分钟

**Comment by Mapaler** [comment]
每次修改一个字母都要一分钟的话，真麻烦，还是Git提交修改比较节约能源。

**Comment by OpportunityLiu** [comment]
是，这样不是更易用吗嘛
更改生效一分钟，但是这中间你可以继续改其它的，不影响。
就算是改当前的，也可以从Web service单独拉取单个标签的最新结果。

所以从编辑的角度来讲其实无所谓，而从使用的角度，一分钟并不是很要紧

**Comment by chocolatl** [comment]
挺好的，以后可以把贡献翻译的功能集成到其它APP上

**Comment by Mapaler** [comment]
https://github.com/kiootic/pad-resources
求教这个项目要怎么才能配置成功，我用yarn install就始终卡在node-npy rebuild。

**Comment by Mapaler** [comment]
看了一下午的prototype
还是不知道怎么实现Window
有没有办法实现一个Window类，new Window()就返回一个定义好内容的DOM，然后这个Window直接修改属性就能修改显示的内容。这个Window还可以同时打开多个。
目前我是用函数每次都return 一个新的div，每个div上都是私有的方法。

**Comment by chocolatl** [comment]
前端不是怎么方便怎么来么

**Comment by Mapaler** [comment]
现在就是不能复用变得不方便了，以前只有一个Window，现在想做无数个了。

**Comment by chocolatl** [comment]
前端交互还是Modal这种同时只能操作一个的组件用的比较多，如果是多个同时交互的Window貌似很少见。我只见过这个UI库提供了Window组件的<https://metroui.org.ua/windows.html>

**Comment by Mapaler** [comment]
这还要用JQ呢，我在想尽量别用库。
再试试用一个外部对象，属性里放dom的模式吧。

**Comment by Mapaler** [comment]
刚才自己拆Switch左手柄把漂移修复了

**Comment by Mapaler** [comment]
E站关了？

**Comment by chocolatl** [comment]
<http://boards.4chan.org/h/thread/5411286>
好像是真的😭

**Comment by xioxin** [comment]
表站可以打开 里站打不开了

**Comment by xioxin** [comment]
~试了 只是论坛挂了，包括登录。~
~已经登录过的里站可以正常使用。~

~保存好自己的饼干。~

**Comment by Mapaler** [comment]
我是看里站都503了

**Comment by dawn-lc** [comment]
里站确认关闭了

**Comment by Mapaler** [comment]
这个项目已经没啥意义了吧

**Comment by chocolatl** [comment]
看看有没有人接盘吧

**Comment by dawn-lc** [comment]
> 看看有没有人接盘吧

但愿吧。

**Comment by xioxin** [comment]
EX 活了

**Comment by chocolatl** [comment]
🎉

**Comment by OpportunityLiu** [comment]
发生啥了，有官宣吗？

**Comment by dawn-lc** [comment]
复 活 节（确信）

**Comment by chocolatl** [comment]
> Update: I'm looking into various alternatives based on information and suggestions from a variety of people. But just to clarify; if a fully intact live version of the site cannot be made available, then the necessary data to clone it will be made available instead.

> Update 2: Work is underway on both a Plan A and a Plan B with different trade-offs for resiliency and usability, but these things aren't done overnight, especially over the weekend. We can only ask that people remain patient for now. We encourage third-party efforts to increase redundancy for potential future events, and both of the plans in progress will be able to provide missing/ongoing data for this when they are ready.

> Update 3: Plan A is only awaiting a server delivery at this point. Plan B is a fairly major design/coding/setup undertaking that I'm mostly advising on, and could easily take another week to complete.

**Comment by Mapaler** [comment]
就是那个著名的瑞士死宅吗？

**Comment by chocolatl** [comment]
这种消息当八卦消息看看就完事了

**Comment by xioxin** [comment]
https://chrome.google.com/webstore/detail/ehsyringelite/mbhdcfeopadbmjnlbpcallmalcefnbbb
看我吧啥上架了，在某宝奸商花了60块激活了账户 😂

**Comment by xioxin** [comment]
![image](https://user-images.githubusercontent.com/5716100/62410080-7419ea00-b613-11e9-8e1f-871e0d2eaca3.png)
增加标签描述

**Comment by chocolatl** [comment]
有竖杆的标签没有处理啊

**Comment by xioxin** [comment]
![image](https://user-images.githubusercontent.com/5716100/62410479-b134ab00-b618-11e9-9237-ca7d2bf23f45.png)
搞定

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/62792389-c3738500-bb01-11e9-820e-f759b14e874c.png)
只要有一堆 badge，项目就看起来特靠谱？

**Comment by xioxin** [comment]
然而并没有

**Comment by Mapaler** [comment]
坏鸽图标太小了
![图像 2](https://user-images.githubusercontent.com/6565860/62796009-a4c5bc00-bb0a-11e9-93f4-5b2d090c8a91.png)
搞个这么大的才好注意
![图像 1](https://user-images.githubusercontent.com/6565860/62795997-9c6d8100-bb0a-11e9-8122-7df033f3c90a.png)

**Comment by Mapaler** [comment]
![image](https://user-images.githubusercontent.com/5716100/62419351-be9d7400-b6b0-11e9-86d3-680436973176.png)
@xioxin 这是你自己画的吗？

**Comment by Mapaler** [comment]
![image](https://user-images.githubusercontent.com/5716100/62419351-be9d7400-b6b0-11e9-86d3-680436973176.png)
@xioxin 这是你自己画的吗？

**Comment by xioxin** [comment]
不是

**Comment by Chihaya7** [comment]
EhViewer发生了什么情况?突然Archived

**Comment by OpportunityLiu** [comment]
hippo想换个项目。。。

**Comment by Mapaler** [comment]
单个小脚本想发在项目组的话，必须新建仓库吗？

**Comment by OpportunityLiu** [comment]
为啥不建呢？

**Comment by Mapaler** [comment]
@OpportunityLiu 每个脚本建个仓库感觉好浪费

**Comment by OpportunityLiu** [comment]
那你可以专门件一个仓库存各种脚本

**Comment by OpportunityLiu** [comment]
https://github.com/EhTagTranslation/UserScripts

**Comment by Mapaler** [comment]
> 
> 
> https://github.com/EhTagTranslation/UserScripts

能不能直接从这个项目fork过去，就能保留以前的提交了

**Comment by OpportunityLiu** [comment]
@Mapaler 弄好了

**Comment by Mapaler** [comment]
@xioxin 我把ETS迁移到了新的数据库去了，但是Sleazy Fork上没有更新，你没有设webhook吗？

**Comment by Mapaler** [comment]
@OpportunityLiu 你有没有Sleazy Fork的账号，我把你添加到作者里，这样你也可以编辑说明了。

**Comment by Mapaler** [comment]
EhViewer有没有什么新的fork啊？

**Comment by Mapaler** [comment]
再次新年快乐

**Comment by Mapaler** [comment]
exhentai域名是有几天都进不去了，有谁知道怎么回事？
<hr>
刚才一刷新又进去了

**Comment by Tmwhmk** [comment]
EhViewer是什么状况，作者是想重现构建还是已经弃坑啊

**Comment by OpportunityLiu** [comment]
> 
> 
> EhViewer是什么状况，作者是想重现构建还是已经弃坑啊

早弃坑了啊
