### ISSUE TITLE
关于部分tag翻译的改正建议

### ISSUE THREAD

**Issue by sdshdv** [Mapaler/EhTagTranslator#51]
使用过程中发现一些明显错误的翻译,
nun翻译成修女服   应该改成:修女
shemale翻译成女雄(这个真是让人哭笑不得) 应该改成:人妖
masked face翻译成假面,这个我觉得不行,毕竟戴口罩的时候也要用这个tag  还是老老实实的翻译成"蒙面"吧
femdom翻译成女性支配,会让萌新以为是支配女性的意思, 建议改成"女性主导"

希望改正一下,谢谢

**Comment by Mapaler** [comment]
nun标签存在于服装类而非人物类，不需要本身是修女，只要是穿着修女服就可以打这个标签。
![screenshot 2019-02-25 16 03 36](https://user-images.githubusercontent.com/6565860/53322637-f42a7e00-3916-11e9-9bba-fc457e7aaceb.png)

shemale的维基百科翻译就是女雄，性别相关tag非常多，很不好区分。目前人妖用在 `male:cuntboy`。
![screenshot 2019-02-25 16 00 28](https://user-images.githubusercontent.com/6565860/53322520-98f88b80-3916-11e9-9787-10454f4486c3.png)
![screenshot 2019-02-25 16 00 57](https://user-images.githubusercontent.com/6565860/53322523-98f88b80-3916-11e9-9580-f18a9da4a699.png)

masked face的原文就是假面，TAG的解释也是如此，口罩用这个应该是误用。如果需要你应该建议增加口罩这一TAG。
![screenshot 2019-02-25 16 06 24](https://user-images.githubusercontent.com/6565860/53322774-55eae800-3917-11e9-9e6f-749b56a6bcd8.png)

femdom的译法可以考虑，你可以自己修改Wiki

**Comment by OpportunityLiu** [comment]
不存在什么人物标签，所有看起来是人物的标签全指的是服装
![default](https://user-images.githubusercontent.com/13471233/53323457-2dfc8400-3919-11e9-8e7f-1abae2899649.png)

**Comment by Mapaler** [comment]
奶子也是服装吗？

**Comment by OpportunityLiu** [comment]
至于transgender系的标签，没人能全弄清楚，感觉网站上也是在乱tag

![default](https://user-images.githubusercontent.com/13471233/53323715-e88c8680-3919-11e9-8b34-d11efbf87040.png)

(为啥就没有hefemale

**Comment by OpportunityLiu** [comment]
> 
> 
> 奶子也是服装吗？

那是 纳粹，德棍太多所以从军装里面独立出来了

**Comment by OpportunityLiu** [comment]
> shemale翻译成女雄(这个真是让人哭笑不得) 应该改成:人妖

或许人妖更合适，不过你得先找个词把 `cuntboy` 的坑填上

**Comment by OpportunityLiu** [comment]
![default](https://user-images.githubusercontent.com/13471233/53324738-8da85e80-391c-11e9-857d-fa7e93a3a780.png)

**Comment by OpportunityLiu** [comment]
https://e-hentai.org/tools.php?act=taggroup&mastertag=1103
https://e-hentai.org/tools.php?act=taggroup&mastertag=57544
https://e-hentai.org/tools.php?act=taggroup&mastertag=1067

alises 里更是群魔乱舞

**Comment by sdshdv** [comment]
研究了下百科定义:
hefemale男雄指的是一个女性切掉胸部,保留部分女性器
cuntboy指的是一个男性切掉鸡鸡加上女性器
实际上cuntboy=hefemale,在外观上都是男性上半身女性下半身
所以cuntboy和shemale完全不冲突
又正好E站没有hefemale的tag,所以可以用cuntboy去替代他
所以我建议这样翻译:
cuntboy翻译成人妖♀
shemale翻译成人妖♂

**Comment by sdshdv** [comment]
或者根据原本的性别,将这两个的翻译反过来
cuntboy原本是男的,所以翻译人妖♂
shemale原本是女的,所以翻译成人妖♀

**Comment by Mapaler** [comment]
@sdshdv 是男雌，不是男雄。

**Comment by OpportunityLiu** [comment]
已经修正
