### ISSUE TITLE
E站改版了，点击页面上方的”EhTagTranslator“选项无反应。

### ISSUE THREAD

**Issue by AcerolaShinobu** [Mapaler/EhTagTranslator#52]
Firefox 55.0.3×64
Tampermonkey® v4.8.5847
E绅士翻译注射器💉 1.2.3

**Comment by xioxin** [comment]
近期会解决

**Comment by xioxin** [comment]
已解决
![image](https://user-images.githubusercontent.com/5716100/55338458-5d338180-54d3-11e9-81a3-6893cd6f8fc8.png)

**Comment by AcerolaShinobu** [comment]
出现了一个bug，在Thumbnail模式下（右上方更改），不显示画廊类别的文字，只显示类别的颜色

**Comment by AcerolaShinobu** [comment]
https://s2.ax1x.com/2019/04/02/Ayjjwn.png

**Comment by xioxin** [comment]
已修复

**Comment by Mapaler** [comment]
![Screenshot 2019-04-02 15 04 09](https://user-images.githubusercontent.com/6565860/55382574-96fa9b80-5558-11e9-9aaa-0b6582a8afab.png)
这里有问题了

不知道怎么样才能把底下的div缩小到让上面的a::before遮住
![Screenshot 2019-04-02 15 14 03](https://user-images.githubusercontent.com/6565860/55383132-01f8a200-555a-11e9-89df-c69f5400f3e1.png)

**Comment by xioxin** [comment]
我不是太理解 
![image](https://user-images.githubusercontent.com/5716100/55400926-c376dd80-5581-11e9-981c-eba8aed654f2.png)

**Comment by Mapaler** [comment]
火狐下有问题，你看看

**Comment by gejila2012** [comment]
为什么我还是点不了..是要下什么别的插件吗360浏览器

**Comment by xioxin** [comment]
> 为什么我还是点不了..是要下什么别的插件吗360浏览器

更新到最新  https://sleazyfork.org/zh-CN/scripts/33136-ehtagsyringe

**Comment by OpportunityLiu** [comment]
又改版了

**Comment by Mapaler** [comment]
![](https://i.imgur.com/MCoQfqg.png)
手机火狐66，也存在电脑版一样的换行问题。

**Comment by xioxin** [comment]
在换行的元素里加个禁止换行试试  `white-space:nowrap;`
自定义样式功能失效了 样式现在是写在代码里

**Comment by Mapaler** [comment]
目前确实是加上了就好了，那是修改代码吗？

**Comment by xioxin** [comment]
你方便的话 就加到代码里吧 别忘改版本号

**Comment by Mapaler** [comment]
既然你去掉了自定义css，那么我就把没内容的按钮的下面的框补全了。

**Comment by 1004452714** [comment]
作者大大你好，我也遇到同样的问题
主页正常，显示高级选项有个小bug，点一下变英文
https://i.loli.net/2019/04/07/5ca8ecdc4fdd9.png

标签翻译全部失效，点上边的按钮也没变化，只有网址多了一个#
https://i.loli.net/2019/04/07/5ca8ecdc4f684.png


使用的插件是4月2号更新的1.3.5版本，浏览器是chrome73.0.3683.103版本
https://sleazyfork.org/zh-CN/scripts/33136-ehtagsyringe

**Comment by Mapaler** [comment]
第一个应该无法解决，点了之后网页内容被重写了。

标签的问题你有没有重新获取翻译数据？

**Comment by 1004452714** [comment]
> 第一个应该无法解决，点了之后网页内容被重写了。
> 
> 标签的问题你有没有重新获取翻译数据？

解决了，看了教程才发现要重新获取，一直以为直接更新就好了，感谢！
