### ISSUE TITLE
希望标签编辑栏增加提示

### ISSUE THREAD

**Issue by Mapaler** [Mapaler/EhTagTranslator#54]
![Screenshot 2019-04-04 21 51 42](https://user-images.githubusercontent.com/6565860/55561053-11c3e200-5724-11e9-9f8d-fa6d90f7f877.png)
希望这个编辑栏也能用中文搜索标签，每次都需要去另一个窗口搜索标签太麻烦了。
要是能把标签区域fix浮动起来编辑，就更方便了。

**Comment by xioxin** [comment]
今晚解决

**Comment by Mapaler** [comment]
我的改动还没合并进主分支，你一并看看
https://github.com/Mapaler/EhTagTranslator/pull/53

**Comment by xioxin** [comment]
解决

**Comment by OpportunityLiu** [comment]
是不是该改用官方的API了？
seven332/EhViewer#589

**Comment by Mapaler** [comment]
官方的又不支持中文搜中文

**Comment by Mapaler** [comment]
@xioxin 能不能实现逗号分隔添加多个时也能提醒呢？一个一个提交的AJAX等待时间太久了。
![Screenshot_2019-04-10_01-37-14](https://user-images.githubusercontent.com/6565860/55821944-30b1e200-5b31-11e9-98d0-7abaef671007.png)

**Comment by Mapaler** [comment]
给`#gd4`添加一个一键切换编辑状态的按钮吧，方便拉到页面下面添加tag
![Screenshot_2019-04-10_02-01-57](https://user-images.githubusercontent.com/6565860/55823618-b1261200-5b34-11e9-8f50-3295b6294f7b.png)
![Screenshot_2019-04-10_02-02-12](https://user-images.githubusercontent.com/6565860/55823646-c1d68800-5b34-11e9-99e7-277618c556f2.png)

**Comment by xioxin** [comment]
> @xioxin 能不能实现逗号分隔添加多个时也能提醒呢？一个一个提交的AJAX等待时间太久了。
> ![Screenshot_2019-04-10_01-37-14](https://user-images.githubusercontent.com/6565860/55821944-30b1e200-5b31-11e9-98d0-7abaef671007.png)

不能 搜索提示使用的h5自带的datalist

**Comment by OpportunityLiu** [comment]
@Mapaler 反正我的客户端是可以，浏览器要实现估计实是要重写逻辑

**Comment by Mapaler** [comment]
@xioxin 那可不可以实现，点击按钮切换到添加复数tag模式，然后在原始tag框下方新增一个输入框，将提示绑给新输入框，新输入框回车时只将内容附加到原始输入框内，最后需要整体提交再去原始tag框回车。这样迂回实现一次添加多个tag。

**Comment by xioxin** [comment]
输入内容 选择标签 <kbd>Ctrl</kbd>+<kbd>A</kbd>, <kbd>Ctrl</kbd>+<kbd>X</kbd>
输入新内容 选择标签 <kbd>,</kbd>,  <kbd>Ctrl</kbd>+<kbd>V</kbd>
