### ISSUE TITLE
建议在EhTagSyringe的sleazyfork的页面描述增加使用方法

### ISSUE THREAD

**Issue by oweaF** [Mapaler/EhTagTranslator#56]
https://sleazyfork.org/en/scripts/33136-ehtagsyringe
这个页面导向的是EhTagTranslator而不是EhTagSyringe的文档，就导致需要看三个文档才能理解怎么用，让人摸不着头脑

**Comment by HKMHD** [comment]
嗯。。。其实一般用户看这个就好了
https://github.com/Mapaler/EhTagTranslator/wiki/EhTagSyringe#%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95

**Comment by OpportunityLiu** [comment]
项目已经迁移到 https://github.com/EhTagTranslation/EhSyringe 转成Chrome和FF插件了。

基本上完全傻瓜化。
