### ISSUE TITLE
项目迁移

### ISSUE THREAD

**Issue by OpportunityLiu** [Mapaler/EhTagTranslator#57]
- [x] 完成编辑器 #50 https://github.com/EhTagTranslation/Editor
- [x] Wiki 版本号变更，添加迁移说明
- [x] 添加详细使用说明 EhTagTranslation/Editor#2
- [x] ETS更新
- [ ] ~~移动当前 Repo？~~
- [x] 几个应用分到独立的 Repo

**Comment by OpportunityLiu** [comment]
@Mapaler @xioxin 
试用一下啊

https://ehtagtranslation.github.io/Editor/

**Comment by Mapaler** [comment]
限制一下行高，图多的拉半天，female可不可以排在male前面，毕竟大部分是搜female的。
最好搜索功能加上命名空间的选择、只搜标题还是包括内容的选择。![](https://i.imgur.com/E3Yk1Hk.png)

**Comment by Mapaler** [comment]
不知道为什么我手机滑倒底部就会自动跳回顶部

**Comment by Mapaler** [comment]
开着NTSF时，预览没有模糊

**Comment by OpportunityLiu** [comment]
> 开着NTSF时，预览没有模糊

这么设计的

> 不知道为什么我手机滑倒底部就会自动跳回顶部

我这没有发现这种情况

> 限制一下行高，图多的拉半天

把不显示图片作为默认设置了

> female可不可以排在male前面，毕竟大部分是搜female的

没有啥意义，这两个命名空间的标签都已经编辑完了，除非要修改，那样可以直接从e站那面跳转过来。。。
事实上搜索功能都用处不大，基本流程应该是  `e站看到一个标签的翻译有问题/没有翻译 -> 直接跳转到编辑页面 -> 编辑提交 -> 回去更新翻译插件的数据库` 列表和搜索就看看行了。

> 、只搜标题还是包括内容的选择。

同上

> 最好搜索功能加上命名空间的选择

这个有了
![图片](https://user-images.githubusercontent.com/13471233/56409845-6a12ec00-62ad-11e9-933f-c063e500d313.png)

**Comment by OpportunityLiu** [comment]
> 不知道为什么我手机滑倒底部就会自动跳回顶部

应该是图片一个一个载入导致页面高度变化直接看github wiki也差不多这种状态

**Comment by OpportunityLiu** [comment]
搜索功能已经修正了，现在原始标签和名称有更高的优先级

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/56455535-f3035380-6391-11e9-87d2-b2c3fa1d6ad5.png)

**Comment by OpportunityLiu** [comment]
@Mapaler 后续咋整？

**Comment by Mapaler** [comment]
我都没在电脑上打开看过，你面向小白用户的编辑说明写了吗？

**Comment by OpportunityLiu** [comment]
你意思要个step by step 那种？

我意思对于小白用户，直接从e站跳转到编辑标签的页面，提交标签回e站就完事了。列表那个就用不上了吧

**Comment by OpportunityLiu** [comment]
翻译插件也需要改

**Comment by Mapaler** [comment]
我是说，就是新人看见这个流程就知道如何注册账号登陆、编辑、添加。不然比现在的还难上手。
目前都暂时并行存在吧，看xioxin确保ETS没问题后再迁移。
而且我觉得老版本也不要直接消失，可以先保留着供旧程序用，加入引流信息关闭编辑把人导向新项目看看情况。

**Comment by DiamondYuan** [comment]
https://github.com/DiamondYuan/vanaheim

mit 协议的项目，想用你们的数据库。

bs 架构的本地管理系统。

**Comment by Mapaler** [comment]
![Screenshot 2019-07-15 14 17 30](https://user-images.githubusercontent.com/6565860/61198185-4e33b080-a70b-11e9-9abb-ce92a1b2d01c.png)
新仓库为什么会出现这种情况呢？Editer没有做判断还是从原始仓库复制过来的时候没修改？

**Comment by OpportunityLiu** [comment]
应该是程序的问题，我看下

**Comment by OpportunityLiu** [comment]
貌似删除线是GFM的语法，所以并没有处理，实际上这面解析的时候是否转义都不会有删除线

**Comment by Mapaler** [comment]
原Wiki就是\~没写右斜杠，被解析成了<del>，我debug时发现的。新项目我就没改了。

**Comment by Mapaler** [comment]
github的readme解析会变成删除线，所以ETB会报错未知nodeName（就是用来检查格式错误的）。

**Comment by OpportunityLiu** [comment]
迁移过去就直接用github release了，那里没有这个问题

**Comment by Mapaler** [comment]
如果是这样那么其实已经没有任何保留旧有格式的理由了吧，直接全部用json储存，editer来编辑不就行了吗，反正能直接改源码的也都懂json。

**Comment by OpportunityLiu** [comment]
diff。。
再说现在用的也挺好

**Comment by OpportunityLiu** [comment]
写了个使用说明 https://github.com/EhTagTranslation/Editor/wiki ，说实话不擅长写这种玩意。

**Comment by Mapaler** [comment]
wiki图片可以用相对地址的吗？

**Comment by OpportunityLiu** [comment]
不能吗？

**Comment by Mapaler** [comment]
我之前一直用的是绝对地址，每次还要去算，特别麻烦……

**Comment by Mapaler** [comment]
那么什么时候开始项目迁移啊

**Comment by OpportunityLiu** [comment]
等EhSyringe再发一个版本就差不多了吧

**Comment by OpportunityLiu** [comment]
@Mapaler 加了项目迁移说明

但是最主要的是更新userscript，在里面提醒用户迁移。估计没几个人来 GitHub 看的。

**Comment by OpportunityLiu** [comment]
然后 Wiki 编辑权限也可以关了

**Comment by Mapaler** [comment]
不移动repo了吗？

**Comment by OpportunityLiu** [comment]
重定向可能有坑，反正不准备再改了

**Comment by Mapaler** [comment]
那么新项目组的历史应该写在哪里？

**Comment by OpportunityLiu** [comment]
https://github.com/EhTagTranslation/Database/wiki/%E6%95%B0%E6%8D%AE%E5%BA%93%E7%BB%93%E6%9E%84%E7%89%88%E6%9C%AC%E4%BF%A1%E6%81%AF

**Comment by OpportunityLiu** [comment]
或者你可以新建个wiki页面来写

反正不要改主repo了，一改就要发布下载啥的，能不动就不动吧

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/63238234-ffcc8100-c277-11e9-9f9a-e9e6fe4ec558.png)
在这里加上迁移说明吧

@Mapaler @xioxin

**Comment by xioxin** [comment]
嗯

发自我的iPhone

**Comment by Mapaler** [comment]
> 
> 
> ![图片](https://user-images.githubusercontent.com/13471233/63238234-ffcc8100-c277-11e9-9f9a-e9e6fe4ec558.png)
> 在这里加上迁移说明吧
> 
> @Mapaler @xioxin

那么脚本要在新组织建一个仓库来存吗，还是继续在原来的地方更新？

**Comment by OpportunityLiu** [comment]
脚本就停更了啊，你还要继续？以后都在 EhTagTranslation/EhSyringe 里面搞好了

**Comment by Mapaler** [comment]
我的脚本是不继续加新功能，但是支持了新数据库，如果想用还是可以继续用。
目前就是TAG编辑辅助工具还没有添加EhSyringe支持。

你增加了##的R18G模式，数据库版本改不改？

**Comment by OpportunityLiu** [comment]
不是已经改成5了？你意思变成6？

**Comment by Mapaler** [comment]
不改应该也没什么问题，反正老的脚本识别不出来，新的也只有一个翻译项目。

**Comment by xioxin** [comment]
> > ![图片](https://user-images.githubusercontent.com/13471233/63238234-ffcc8100-c277-11e9-9f9a-e9e6fe4ec558.png)
> > 在这里加上迁移说明吧
> > @Mapaler @xioxin
> 
> 那么脚本要在新组织建一个仓库来存吗，还是继续在原来的地方更新？

继续保留再原来的位置,

**Comment by xioxin** [comment]
> 我的脚本是不继续加新功能，但是支持了新数据库，如果想用还是可以继续用。
> 目前就是TAG编辑辅助工具还没有添加EhSyringe支持。
> 
> 你增加了##的R18G模式，数据库版本改不改？

你可以吧还继续维护的代码新建一个新项目

**Comment by OpportunityLiu** [comment]
先到这里吧，后续可以在那边讨论
