### ISSUE TITLE
ETS 更新

### ISSUE THREAD

**Issue by OpportunityLiu** [Mapaler/EhTagTranslator#60]
- [ ] 迁移数据源
- [ ] 在E站选中标签后添加跳转到编辑器的链接

**Comment by OpportunityLiu** [comment]
这活谁来干啊
我看了下ETS的代码，实在太乱了

@xioxin  @Mapaler

**Comment by Mapaler** [comment]
我是个业余的，ETS的面向对象的写法我直接看不懂的。

**Comment by OpportunityLiu** [comment]
既然已经推倒重来了这个就用不着了

EhTagTranslation/EhSyringe#3
