### ISSUE TITLE
Archlinux firefox67 + violentmonkey 使用 EhTagSyringe 遇到问题

### ISSUE THREAD

**Issue by KCCat** [Mapaler/EhTagTranslator#63]
在github页面遇到CSP问题,按照提示修改 violentmonkey 的 Default injection mode 选项依然无法解决.

切换到 EhTagBuilder 虽然也有提示CSP但没有发现明显问题.

在hentai页面点击EhTagSyringe 看不见菜单,在控制台可以看到相关元素增加,但是不显示.

**Comment by Mapaler** [comment]
免费的 violentmonkey 没有什么开发的积极性的，我们这个项目也是免费的，xioxin 也有自己的工作，想要正常用 EhTagSyringe 还是用Tampermonkey吧。
自己有能力的人可以帮助改写兼容。

**Comment by OpportunityLiu** [comment]
已经转成浏览器插件了 https://github.com/EhTagTranslation/EhSyringe
