### ISSUE TITLE
FAKKU聯動Banner導致Tag顯示問題

### ISSUE THREAD

**Issue by sorakirahk** [Mapaler/EhTagTranslator#64]
比如畫廊：https://exhentai.org/g/958080/daf92851f0/
![Sora_2019-05-31_12-20-42](https://user-images.githubusercontent.com/24854146/58681346-8de24b00-839e-11e9-9958-3166df145381.png)

打開顯示雙語標籤後超出得更多，都跑都到thumbnails上面了

**Comment by Mapaler** [comment]
我紧急修了一下问题。
@xioxin 你看看要怎么正确的修改。 2b5a29e325de0698b40a7acdb3004497d736e53c

**Comment by xioxin** [comment]
你的修改要是没问题就直接传上去吧，我在公司没办法浏览E站 😂
