### ISSUE TITLE
Tag开启双语显示后长度过长导致显示问题

### ISSUE THREAD

**Issue by sorakirahk** [Mapaler/EhTagTranslator#65]
比如这个Tag
![1](https://user-images.githubusercontent.com/24854146/58772596-61bc0980-85ec-11e9-9324-817983f3a52a.jpg)
![2](https://user-images.githubusercontent.com/24854146/58772597-62ed3680-85ec-11e9-8670-f8cbcaf95d34.jpg)

**Comment by Mapaler** [comment]
要么就别开双语，要么就将就一下，它就是有那么长，目前没有解决办法。

**Comment by sorakirahk** [comment]
> 要么就别开双语，要么就将就一下，它就是有那么长，目前没有解决办法。

了解

**Comment by OpportunityLiu** [comment]
都是业界的错，总有一天不开双语也会变成这样的

**Comment by Mapaler** [comment]
确实现在的轻小说取名都乱七八糟的
