### ISSUE TITLE
新的翻译替换方法

### ISSUE THREAD

**Issue by xioxin** [Mapaler/EhTagTranslator#66]
https://gist.github.com/xioxin/d70257d290d16d9a7422ede048699e80
核心代码仅37行

**Comment by Mapaler** [comment]
textContent替换？不就是JS吗？

**Comment by xioxin** [comment]
嗯 低延迟 不需要等待dom完全加载在加载过程直接替换

**Comment by OpportunityLiu** [comment]
挺好的，顺便可以把数据源迁移过去啊

**Comment by Mapaler** [comment]
所以谁能告诉我原理吗:joy:

**Comment by xioxin** [comment]
MutationObserver 是dom监听器 dom发生变化的时候会触发, 甚至ui是被其他js修改了也会触发翻译
但是Tampermonkey加载代码是异步的 偶尔可能加载慢了 所以额外加一个createNodeIterator来遍历已经加载了的dom

**Comment by Mapaler** [comment]
那么浏览器支持度怎么样？
新增的tag会不会被修改？

**Comment by xioxin** [comment]
https://caniuse.com/#search=MutationObserver
会被修改

**Comment by Mapaler** [comment]
用JS就可以随意调控样式了。
是不是需要再做一个解释面板？

**Comment by xioxin** [comment]
打算不再使用Tampermonkey 直接使用chrome插件开发

**Comment by Mapaler** [comment]
其实我也想建议你做成插件，但是能过审吗？

**Comment by xioxin** [comment]
肯定过不了审 直接手动安装就好 
刚刚试验了下 感觉页面就像原生中文一样 不会有先显示英文再变成中文的情况

**Comment by xioxin** [comment]
[EhSyringeLite.zip](https://github.com/Mapaler/EhTagTranslator/files/3325019/EhSyringeLite.zip)

**Comment by Mapaler** [comment]
这样的话更新程序不是很麻烦吗

**Comment by xioxin** [comment]
这无所谓

**Comment by xioxin** [comment]
[EhSyringeLiteTest2.zip](https://github.com/Mapaler/EhTagTranslator/files/3325641/EhSyringeLiteTest2.zip)


![image](https://user-images.githubusercontent.com/5716100/60105105-4da39c00-9795-11e9-8c32-514b38adf063.png)
![image](https://user-images.githubusercontent.com/5716100/60105226-8774a280-9795-11e9-8211-4808c2aca889.png)
![image](https://user-images.githubusercontent.com/5716100/60105254-952a2800-9795-11e9-9dd2-5d43a058ddf6.png)
![image](https://user-images.githubusercontent.com/5716100/60105287-a4a97100-9795-11e9-966e-df6b7d3e242d.png)
![image](https://user-images.githubusercontent.com/5716100/60105357-c4d93000-9795-11e9-9d4b-e12debfbaf35.png)
![image](https://user-images.githubusercontent.com/5716100/60106665-30bc9800-9798-11e9-884e-816c4e1791aa.png)
![image](https://user-images.githubusercontent.com/5716100/60106724-4467fe80-9798-11e9-9546-1721d0f1568e.png)

**Comment by Mapaler** [comment]
那么，旧有的脚本是停止开发吗？

**Comment by Mapaler** [comment]
希望考虑一下火狐的扩展，因为安卓上火狐可以装扩展的，手机上可以装Tampermonkey然后用ETS

**Comment by xioxin** [comment]
火狐不是兼容chrome的扩展吗

**Comment by Mapaler** [comment]
火狐只是使用WebExtention API，不能说兼容Chrome，很多Chrome的扩展火狐用不了的。

**Comment by xioxin** [comment]
![GIF](https://user-images.githubusercontent.com/5716100/60812493-310b5900-a1c4-11e9-85f7-1d4212765156.gif)

**Comment by Mapaler** [comment]
不是说不支持搜索多个吗？

**Comment by xioxin** [comment]
自己写的不是 datalist

**Comment by Mapaler** [comment]
整个下拉栏都是自己写的？用dom实现的还是用的系统list

**Comment by xioxin** [comment]
是dom 没有现成的接口

**Comment by Mapaler** [comment]
这样得多好多dom哦，感觉会很卡。
既然都是自己做的话，可以把图标也显示出来了。

**Comment by xioxin** [comment]
不会的卡 不是所有的tag都加载 只有搜索到的才会加载 并且最多加载50条
图片可以显示
![QQ截图20190708214625](https://user-images.githubusercontent.com/5716100/60815389-1cca5a80-a1ca-11e9-8038-d1fcae3c81c2.png)

**Comment by Mapaler** [comment]
不过这样的话，我写的那个编辑tag的辅助工具还不好兼容了

**Comment by xioxin** [comment]
怎么讲? 不是很理解

**Comment by Mapaler** [comment]
因为是读取的datalist来搜索，下面那个标签编辑工具，要不你把这个功能也写进去？
浮动窗口那部分不用写，这个脚本可以继续用，就是搜索数据这部分肯定是无法读取另一个脚本的变量的。
https://github.com/Mapaler/EhTagTranslator/wiki/ETTWikiHelper#%E6%A0%87%E7%AD%BE%E7%BC%96%E8%BE%91%E5%B7%A5%E5%85%B7

**Comment by xioxin** [comment]
```javascript
JSON.parse(window.localStorage.getItem('tag-list'))
```

![image](https://user-images.githubusercontent.com/5716100/60817519-69b03000-a1ce-11e9-9874-e70ab5151f00.png)

**Comment by xioxin** [comment]
没想到吧
![image](https://user-images.githubusercontent.com/5716100/60818020-5f426600-a1cf-11e9-83d1-381c200a3f83.png)

**Comment by Mapaler** [comment]
这次没用GM的API来储存数据了吗？

**Comment by OpportunityLiu** [comment]
local storage不是可以直接塞对象的？

**Comment by xioxin** [comment]
![image](https://user-images.githubusercontent.com/5716100/60821866-f7901900-a1d6-11e9-942d-408f3fa6ba6b.png)
并不能


不是油猴子写的 肯定不是GM啊
至于为什么不用插件的chrome.storage.local 来存储 因为这个接口是异步的 没办法在dom渲染之前取出来
所以还是用了 window.localStorage

但是跨域下载只能在 background页 中进行, 但是却不能访问window.localStorage

所以就要发消息到 background页 进行下载, 下载好后存入 chrome.storage.local, 提示用户手动刷新
前台页面检测到数据,转存入window.localStorage, 再自动刷新页面加载数据进行页面翻译 ,

**Comment by xioxin** [comment]
我现在访问github巨慢无比 推代码推了好几次了才刚成功 挂代理都慢

**Comment by xioxin** [comment]
![image](https://user-images.githubusercontent.com/5716100/60823624-87839200-a1da-11e9-9c7a-cc09b9067730.png)

**Comment by Mapaler** [comment]
我也是访问github慢

**Comment by Mapaler** [comment]
我觉得这已经不lite了，比原来的更复杂啊。你的名字应该反过来。或者直接叫ETS2

**Comment by xioxin** [comment]
确实一点不lite

**Comment by xioxin** [comment]
试了下火狐 除了下载数据时候 发送桌面通知有个更新通知接口不兼容其他都可以正常使用

**Comment by Mapaler** [comment]
要不就叫Extention，ETE。
安卓火狐可以用扩展啊，可以usb调试连接后用桌面版连接进行调试，所以考虑一下安卓手机使用不？

**Comment by xioxin** [comment]
苹果用户 没有android 手机

**Comment by Mapaler** [comment]
呼吁苹果允许第三方浏览器

**Comment by xioxin** [comment]
我没有办法测试手机插件 你们有条件可以试试

**Comment by Mapaler** [comment]
https://www.npmjs.com/package/wpe-webgl
这个库是不是没法在Windows下安装啊？

**Comment by xioxin** [comment]
chrome 插件市场可是上架E站相关插件
搜索hentai已经有一些插件的 ，但是上架需要有外币信用卡激活账户并支付5美元
我并没有信用卡

**Comment by Mapaler** [comment]
![Screenshot 2019-07-15 14 42 39](https://user-images.githubusercontent.com/6565860/61198979-d071a400-a70e-11e9-8697-79ff0545e4f3.png)
我想测试一下ETSL，可是安装不上webpack-cli要怎么办啊

**Comment by xioxin** [comment]
如果只是想试一下的话 build目录里是一份已经编译好的

**Comment by Mapaler** [comment]
没有TAG详情的吗？也没有控制面板。

**Comment by xioxin** [comment]
现在只有 翻译 tag 和tag提示

**Comment by xioxin** [comment]
你如果想试试的话 也可以开发
在src中创建新的ts文件


加入到编译入口
/webpack.config.js
![image](https://user-images.githubusercontent.com/5716100/61203860-2ac63100-a71e-11e9-8d04-9eeda5957b79.png)


修改插件配置 插入脚本
/build/manifest.json
![image](https://user-images.githubusercontent.com/5716100/61203882-3d406a80-a71e-11e9-8ec8-e48ae26b8063.png)

**Comment by xioxin** [comment]
webpack-cli 问题 你可以试试

`npm install -g webpack-cli`

在全局安装一份

**Comment by Mapaler** [comment]
我觉得应该不行，我连JS都没搞懂，更搞不懂TS了。
目前还在每次提示缺一个包，不断地装新的包，为什么就不能自动一次性安完呢

**Comment by xioxin** [comment]
你有 npm install 安装以下依赖吗

**Comment by xioxin** [comment]
TS只是在JS的基础上增加了 类型检测，没什么太大的变化。半个小时就能学会。

**Comment by Mapaler** [comment]
不知道，我最近自己写一点的时候，想用的依赖的都需要那个编译，总是失败，所以最后是当JScript一样全用的原生的。
要是Windows能用node替换掉cscript.exe的JScript解释器就好了，几百年没更新了。

**Comment by Mapaler** [comment]
![Screenshot 2019-07-15 19 13 04](https://user-images.githubusercontent.com/6565860/61212349-96b39400-a734-11e9-8515-76411e0e250c.png)
我执行了`npm start`就卡在这里，而且代码都变了，比如`\r\n`变成了`\n`

**Comment by xioxin** [comment]
这就是已经运行了 你编辑ts文件 build目录的js文件就会跟着变

**Comment by xioxin** [comment]
![GIF2](https://user-images.githubusercontent.com/5716100/61219206-4e04d680-a746-11e9-937b-30e59617acb7.gif)
地址栏也可以直接用

**Comment by Mapaler** [comment]
地址栏可以用什么？

**Comment by xioxin** [comment]
标签提示

**Comment by xioxin** [comment]
新项目已建立, 相关问题移步 https://github.com/EhTagTranslation/EhSyringe 讨论
