### ISSUE TITLE
图标高度问题 导致标签错乱

### ISSUE THREAD

**Issue by xioxin** [Mapaler/EhTagTranslator#7]
http://exhentai.org/g/935251/eb53b8c8ba/?p=1

**Comment by Mapaler** [comment]
![img](http://ww1.sinaimg.cn/large/6c84b2d6jw1f44lzql41nj20go0aqtas.jpg)
哪里错乱了，你要贴个图啊。
不想要图标可以用最新版的设置里去掉生成中文名里的图片。

**Comment by xioxin** [comment]
我不知道为啥总是上传不了图片 提示 `Something went really wrong, and we can’t process that file.`
`#ta_female:*`div 没图片的整体高度19px 有图片的高度20px

**Comment by Mapaler** [comment]
你在哪儿上传图啊，我完全不明白你在做什么

**Comment by xioxin** [comment]
![图片](https://dn-coding-net-production-pp.qbox.me/528ad62a-074c-4ee3-8e31-400d3041f690.png)

**Comment by xioxin** [comment]
我直接截图在输入框ctrl+v粘贴过一段时间就提示我上传失败 
我在别的站点穿的 所以打了马 不知道有没有防盗链能不能显示

**Comment by Mapaler** [comment]
什么输入框ctrl+v，完全不知道你在说哪里。你是要做什么？我传图都是传的新浪相册，而且都是上传文件，不要粘贴剪切板，粘贴剪切板得到的都是24位位图，又大又丢失透明。你不会用也可以传GitHub，你回复的时候把图片文件拖进来等上传就行了。

**Comment by xioxin** [comment]
我是回复你这一句 `哪里错乱了，你要贴个图啊。` 解释为啥我没附带图

**Comment by Mapaler** [comment]
因为默认的文字高度都是12px，我之前一次测试发现13px也没出问题，所以就做的13px的Icon，可能是字体区别？毕竟12px高度限制太大了，Tag的意思很难表现出来。所以规定了最大16px，毕竟大多数图标都是最小16px的。
要解决要么重新画图，要么改CSS，要么不生成Icon。

**Comment by xioxin** [comment]
改css吧

**Comment by Mapaler** [comment]
GitHub图片传不了是因为你的网络无法访问亚马逊CDN，我家里的铁通就得翻墙上。
