### ISSUE TITLE
标签备注位置错乱

### ISSUE THREAD

**Issue by dodying** [Mapaler/EhTagTranslator#8]
我遇到的问题
本来不想发这个issues的（感觉仅靠css，这个问题无法解决），但是看到了[#7](https://github.com/Mapaler/EhTagTranslator/issues/7)，还是决定发上来，也许就解决了呢。
边看图片，边阐述。
图片里的本子地址是[Collection of Person and Model Ships (Kantai Collection) - E-Hentai Galleries](http://g.e-hentai.org/g/832917/587671e855/)【Non-H，可放心打开】

![1](https://cloud.githubusercontent.com/assets/13816909/15506271/9038f2be-21f9-11e6-8dae-8f80deb3625d.jpg)
当#taglist里的滚动条不动，备注就显示在标签旁
![2](https://cloud.githubusercontent.com/assets/13816909/15506254/7f7948e8-21f9-11e6-914b-4a2334a64877.jpg)
当#taglist里的滚动条滚动一些（应该是显示在了当滚动为0时位置的旁边）
![3](https://cloud.githubusercontent.com/assets/13816909/15506278/97c4b0a4-21f9-11e6-9650-c8c303605986.jpg)
当#taglist里的滚动条滚动再多一些（...）

**Comment by xioxin** [comment]
增加下面的样式试一试

```
div.gt,
div.gtw,
div.gtl{
    line-height: 19px;
    height: 19px;
    overflow: hidden;
}
```

**Comment by dodying** [comment]
添加到css文件里？
没效果啊

**Comment by xioxin** [comment]
放在 Tag通用样式 通用样式 
我这里不存在仅文字时候错行问题 我这里只有带图标的情况错行
我统一高度并设置溢出隐藏后恢复正常 
你用的什么浏览器

**Comment by dodying** [comment]
还是不行
火狐46

**Comment by xioxin** [comment]
我用的google 我尝试下火狐

**Comment by xioxin** [comment]
已测试 代码正常运作 你肯定是忘记重新生成样式了 :joy:

**Comment by Mapaler** [comment]
你为什么这么熟练啊，这些引用另一个帖子和恢复到另一个帖子是怎么调出来的啊，我到处都没找到。

你的问题是因为，2.0.1时，简介框位置是fix，但是top没有设置，也就是tag初始位置相对浏览器的位置。于是移动网页不会改变框的位置，下面的就永远在下面，2.0.2我改成了top:0px;，让框始终置顶来解决，但你没有重置设置，因此还是2.0.1的CSS。楼上的多半一开始就用的2.0.2吧？或者重置过了。
本来absolute是最吼的，然而用这个就无法跳出#taglist框。

他做的那个CSS不错，你可以用用看。明天再改进一下。

**Comment by dodying** [comment]
额，确实，重置后再生成就没有问题了
至于引用，很简单，写个网站就行了
`[#7](https://github.com/Mapaler/EhTagTranslator/issues/7)`
